### ISSUE TITLE
[10.0] Error in following readme report_py3o

### ISSUE THREAD

**Issue by JordyRitzen** [OCA/reporting-engine#104]
When following the readme of the module for the installation an error wil occure on `pip install service-identity`. This is because of missing libraries.

The following command will solve this error by installing the dependencies. (this was needed because I installed it on a clean system)
`sudo apt-get install build-essential libssl-dev libffi-dev python-dev`

**Comment by pedrobaeza** [comment]
Thanks for the clarification, but this is a platform dependent instruction that might differ even between different Ubuntu versions, so the README shouldn't document this kind of thinks IMO.
