### ISSUE TITLE
Invoice report using Py3o

### ISSUE THREAD

**Issue by medhajoshi** [OCA/reporting-engine#123]
We installed report_py3o on odoo 10 .
We followed the instructions as per guidelines and getting error while printing customer invoice.

"partner_id" not defined: (<class 'genshi.template.eval.UndefinedError'>, UndefinedError('"partner_id" not defined',), <traceback object at 0x7f0f9b0cee60>)

**Comment by alexis-via** [comment]
Have a look at my sample reports, it should help:
https://github.com/akretion/odoo-py3o-sample-report/tree/10.0/account_invoice_report_py3o

**Comment by medhajoshi** [comment]
Thank you Alexis for the sample report. It has helped us going forward.
I am not clear about defining user field variable names while creating ODT template.
(For eg. some fields py3o.objects._____ and some fields py3o.user.comapny_id.___)
Where could we find the list of the Odoo fields which can be used in ODT template as py3o fields?
Thank you!

**Comment by pedrobaeza** [comment]
This is not an issue, but a question, and the sample should be enough.
