### ISSUE TITLE
Decorated function executed even no module installed

### ISSUE THREAD

**Issue by agb80** [OCA/reporting-engine#13]
Downloaded branch 7.0 from this module to being able to use excel report engine, left the entire folder onto the addons path and restart the server, after that the function decorated with @http.httprequest found on https://github.com/OCA/reporting-engine/blob/7.0/report_custom_filename/controllers/reports.py#L29 start to being executed event the report_custom_filename module is not being enabled on database.

Understand the simplest solution is delete the module from addons path, but wonder if anybody knows why is this behavior and if there is any way to corrected.

Already opened a bug on odoo here: odoo/odoo#6995

**Comment by hugosantosred** [comment]
:+1: It's also happening to us. This behaviour makes impossible to download any file from a report in OpenERP unless you delete the module from addons or install it.

**Comment by pedrobaeza** [comment]
As a workaround has been merged in https://github.com/OCA/reporting-engine/pull/15, I close this one.
