### ISSUE TITLE
py3o report raise" File is not a zip file"

### ISSUE THREAD

**Issue by LiJiaPeng-1** [OCA/reporting-engine#132]
When I user py3o demo report raise "File is not a zip file", I don't know which version of the python module problem

**Comment by lmignon** [comment]
@LiJiaPeng-1 Thank you for the report. Unfortunately it's not possible to figure out what's the problem without more details on how to reproduce the problem.
Can you provide the steps to reproduce the bug on runbot?
https://runbot.odoo-community.org/runbot/143/10.0

**Comment by LiJiaPeng-1** [comment]
runbot is well,so maybe Which modules are different,can give me use the modules' version?

in this line:  template = Template(in_stream, out_stream, escape_false=True)  raise "File is not a zip file"

**Comment by lmignon** [comment]
@LiJiaPeng-1 

> in this line: template = Template(in_stream, out_stream, escape_false=True) raise "File is not a zip file"

It seems that the file provided as template is not an odt file

**Comment by LiJiaPeng-1** [comment]
Thank you answer me,I solve the problem by give a py3o_template_id
