### ISSUE TITLE
error print report demo

### ISSUE THREAD

**Issue by aviqbaihaqy** [OCA/reporting-engine#135]
in menu user, error when print of the report using py3o Demo Report:
running on odoo 10 in debian vagrant.
```
must be string or buffer, not bool: (<type 'exceptions.TypeError'>, TypeError('must be string or buffer, not bool',), <traceback object at 0x7fafd45eb830>)

**Comment by lmignon** [comment]
Thank you for the report. Unfortunately it's not possible to figure out what's the problem without more details on how to reproduce the problem.
Can you provide the steps to reproduce the problem on runbot?
https://runbot.odoo-community.org/runbot/143/10.0
