### ISSUE TITLE
Expected singleton: account.invoice

### ISSUE THREAD

**Issue by medhajoshi** [OCA/reporting-engine#137]
Trying to get report of invoice (account.invoice) using py3o & libreoffice. We are getting errors when multiple products are listed in invoice.

Expected singleton: account.invoice.line(14, 15): (<type 'exceptions.ValueError'>, ValueError('Expected singleton: account.invoice.line(14, 15)',), <traceback object at 0x7fe2de3bef80>)

**Comment by pedrobaeza** [comment]
This is an error in the design of your report, not a problem itself in the engine. Use a loop when needed.

**Comment by medhajoshi** [comment]
We used a for loop like this
py3o://for line in invoice_line_ids
py3o.line.name
py3o:///for

**Comment by alexis-via** [comment]
I confirm it works perfectly well on invoices with multiple products.
