### ISSUE TITLE
[10.0] xlsx report_type not working

### ISSUE THREAD

**Issue by krueger80** [OCA/reporting-engine#138]
There seems to be issues with the Excel Export module (report_xlsx).

On runbot, go in Settings-->Reports-->Reports.
Select Trail Balance and edit. Change PDF type to xlsx.
Go in Accounting-->PDF Report-->Trial Balance, keep the default parameter and click Print.
You get the following error:
Unknown report type: xlsx: (<type 'exceptions.NotImplementedError'>, NotImplementedError(u'Unknown report type: xlsx',), <traceback object at 0x7f1d32210d88>)

**Comment by pedrobaeza** [comment]
You are misunderstanding how to use the module. You don't have to change the type of the report that way. You need to develop a report which uses it. Check account_financial_report_qweb for an example.
