### ISSUE TITLE
Unknown report type: xlsx

### ISSUE THREAD

**Issue by binhdinhjsc** [OCA/reporting-engine#155]

**Comment by pedrobaeza** [comment]
Please give more information.

**Comment by binhdinhjsc** [comment]
I install modul export_stockinfo_xls error Unknown report type: xlsx

**Comment by pedrobaeza** [comment]
I don't even know that module, but you shouldn't install correctly report_xlsx. Any way, it's not a bug in this repository.

**Comment by binhdinhjsc** [comment]
Thank you verry much
