### ISSUE TITLE
[10] Can not delete Custom BI Views

### ISSUE THREAD

**Issue by cgalvezp** [OCA/reporting-engine#158]
When i try no return a custom bi view to draft state i got
**"Cannot rename/delete fields that are still present in views:
Fields: x_bve.invoi.x_amount_total, x_bve.invoi.x_name
View: Graph Analysis"**

And i can not delete the customs.

Thanks

**Comment by sapentia** [comment]
I have the same issue - unable to delete test view on v10

**Comment by astirpe** [comment]
@cgalvezp @sapentia you may want to check the fix proposed in https://github.com/OCA/reporting-engine/pull/191
