### ISSUE TITLE
bi_sql_editor - Add form view

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/reporting-engine#160]
The BI Sql editor could have the capability to add a form view, so that a user can navigate from the tree view to form view and from there to the specific object that may be defined in the query (e.g. a partner, product, sale order, etc..)

**Comment by JordiBForgeFlow** [comment]
cc @aheficent @legalsylvain

**Comment by legalsylvain** [comment]
Hi @jbeficent,

As this module is a BI module, I personaly don't have the need to navigate into each item. (the reason I wrote this module was to manage "big datas"). But well, I'm not against your proposal, and will review your PR if you make one.

regards.

**Comment by JordiBForgeFlow** [comment]
The ability to drill down from the big data to the detail allows a business to reconcile the big numbers. 

So, you have a sales of 1M according to your big data. Oao! But then you drill down and discover that one sales order was incorrectly entereed for 0.99M.

**Comment by legalsylvain** [comment]
:+1: Thanks for the use case.

**Comment by AaronHForgeFlow** [comment]
:+1: It's ok to me as it solves a new use case

**Comment by legalsylvain** [comment]
Hi. 

I just tried the module that is currently being ported on 10.0 and it seems that such feature is native on odoo 10.0. No need to add new form view.

@jbeficent : could you try ? https://github.com/OCA/reporting-engine/pull/206

Feel free to reopen this issue, if you think I'm wrong.

kind regards.
