### ISSUE TITLE
[10.0] report_xlsx Error

### ISSUE THREAD

**Issue by sarahosay** [OCA/reporting-engine#173]
Hi I always get this error whenever I add the functionality to other report in odoo 10:
Unknown report type: xlsx: (<type 'exceptions.NotImplementedError'>, NotImplementedError(u'Unknown report type: xlsx',), <traceback object at 0x7f563407d680>)

Can anyone please give me an example on how to use this module in accounting report? Thank you!

**Comment by pedrobaeza** [comment]
See https://github.com/OCA/l10n-spain/tree/10.0/account_balance_reporting_xlsx
