### ISSUE TITLE
[11.0] Excel File is not Downloading!

### ISSUE THREAD

**Issue by musfiqurcse** [OCA/reporting-engine#178]
I imported the addons `reports_xlsx` to my addons. Everything is working fine. But the file is not downloading. 
The button which trigger the action is
```
    @api.multi
    def export_xls(self):
        context = self._context
        datas = {'ids': context.get('active_ids', [])}
        # ctx = self.report_cash_data()
        ctx= None
        user = self.env["res.users"].browse(self._uid)
        company_name = user.company_id.name
        datas['model'] = 'payslip.report.xls.wizard'
        datas['form'] = self.read(
            ['start_date', 'end_date'])[0]
        datas['form']['context'] = ctx
        datas['form']['company'] = company_name
        if context.get('xls_export'):
            return self.env.ref('custom_addons.excel_report_payroll').render_xlsx(self, data=datas)
```

my report file is
```
  <report id="excel_report_payroll" model="res.partner" string=" " report_type="xlsx"
          name="bs_hr.payslip_report.xlsx" file="res_partner"
          attachment_use="False" />
```

my report python file is 

```
class PartnerXlsx(models.AbstractModel):
    _name = 'report.bs_hr.payslip_report.xlsx'
    _inherit = 'report.report_xlsx.abstract'

    def generate_xlsx_report(self, workbook, data, partners):
        for obj in partners:
            sheet = workbook.add_worksheet('Report')
            bold = workbook.add_format({'bold': True})
            sheet.write(0, 0, obj.name, bold)
```
Is there something i missed ?
Action running successfully 
![file01](https://user-images.githubusercontent.com/7546608/33994494-e27c8b46-e104-11e7-8999-2323759c38c2.png)
First rendering render_xlsx
![first_one](https://user-images.githubusercontent.com/7546608/33995018-c6c278f0-e106-11e7-967d-780dc26a3dbf.png)
Then running successfully create_xlsx_report function
![second_file](https://user-images.githubusercontent.com/7546608/33995055-ea076b86-e106-11e7-9998-eb44ea145d74.png)

I got byte values and return nothing

value which I got byte value and the result says
![currectly returning_value](https://user-images.githubusercontent.com/7546608/33994815-28e6ab56-e106-11e7-8889-ac689bad30ab.png)

 `unexpected EOF while parsing (<string>, line 1)`

**Comment by JordiBForgeFlow** [comment]
You can check how it is done in this module: https://github.com/OCA/account-financial-reporting/pull/367

**Comment by jeroenev** [comment]
same issue here
account-financial-report is not really helpfull
have you found any solution?

**Comment by jeroenev** [comment]
is there really no way to return your own rendered report?
i just want to port my module from odoo10 to odoo11, i used render_xlsx in odoo10 and was able to easily return it
it should be possible to port it to odoo11 without rewriting it from scratch

**Comment by JordiBForgeFlow** [comment]
You can test in runbot the account financial reports in 11.0 that use report_xlsx, and it works fine:
http://3331349-11-0-674e97.runbot1.odoo-community.org/web

![image](https://user-images.githubusercontent.com/7683926/42945967-1287985c-8b6a-11e8-8a9e-24db1711057b.png)

**Comment by JordiBForgeFlow** [comment]
@jeroen7s The module has been successfully ported. As odoo 11 changed it's structure from 10, the report_xlsx had to be adjusted as well. You need to understand how other modules such as account financial reports have been migrated to 11.0.

See also https://github.com/OCA/manufacture-reporting/tree/11.0/mrp_bom_structure_xlsx

The comment that x should be possible without doing y is not really helping anyone. As I show you, many have been able to successfully migrate.

**Comment by jeroenev** [comment]
yeah,
wasn't as big of a deal as i thought, took some rewriting though.
seems like I just didn't properly understood how it worked.
it's working fine now.
though I had to store the wizard data in a model in order to get it when rendering, which was previously not necessary (I could also prepare the data before, store it in a model, and use that to render the excel sheets, but that would require a bigger rewrite as the 'getting data' and 'rendering multiple sheets' logic was mixed, + it would require a lot more disk space)
thanks anyway
