### ISSUE TITLE
[RFC] report_py3o using libreoffice --headless --convert-to

### ISSUE THREAD

**Issue by hbrunn** [OCA/reporting-engine#179]
@alexis-via I think I'm not the only one who is a bit scared by the dependencies of report_py3o when we want document conversions. From studying the code, I don't see a reason why we can't call the libreoffice binary in headless mode to do the conversion after py3o has done its job. Did you try this and it didn't work or does the fusion server have any advantages we want to have that I'm ignorant of? Anyways, I'm of a mind to PR a patch to make this (local libreoffice conversion) an option.

**Comment by Yakulu** [comment]
I guess direct call to LO binary is what @elicoidal has done into [his workaround](https://github.com/Elico-Corp/odoo-addons/blob/10.0/report_py3o_convert_xlsx/controllers/main.py#L49) to get XLSX conversion working with py3o

**Comment by rvalyi** [comment]
@hbrunn I may be wrong but I guess the fusion server would have a speed advantage as Libreoffice is mostly Java based and hence will have a slow startup time (time to allocate lots of RAM and let the JVM optimizations kick in) so server mode would perform much better than a command line call. That being said a degraded command line mode might be welcome.

**Comment by hbrunn** [comment]
thanks for the input everyone, I'll propose a PR then to move the fusion server stuff into its own module, to have minimal dependencies for `report_py3o` in order to spread its usage. Whoever needs the fusion server can install that, others won't be affected

**Comment by hbrunn** [comment]
For the record: The claim about Libreoffice being java is [not entirely true](https://wiki.documentfoundation.org/Development/Java)

**Comment by hbrunn** [comment]
done in #180

**Comment by Yakulu** [comment]
Thanks @hbrunn , great work ! About performance, something like [unoconv](https://github.com/dagwieers/unoconv) might be explored.

**Comment by hbrunn** [comment]
no, that would be reinventing the wheel. If libreoffice startup times are an issue, that's what the fusion server solves for you as @rvalyi pointed out
