### ISSUE TITLE
Blank screen when login (with new module `report_fillpdf`)

### ISSUE THREAD

**Issue by novawish** [OCA/reporting-engine#183]
Impacted versions:
Odoo 11.0

Steps to reproduce:
If the system did not have `pdftk` installed (by using `apt-get install pdftk`) before having module `report_fillpdf` in addons directory. Even when the module was not installed, it will show blank screen after login and we absolutely can not do anything

Current behavior (see screenshot):
![Blank screen](https://i.imgur.com/ppNVYJf.png)

Expected behavior:
Should not raise error when `pdftk` is not present

**Comment by melroy89** [comment]
Agree! But it could be unrelated...

**Comment by JordiBForgeFlow** [comment]
Thanks for reporting. Cc @etobella

**Comment by novawish** [comment]
I also thought it was unrelated in the first time, but then I fixed it by https://github.com/OCA/reporting-engine/pull/184 and it worked (in my case). But I still have doubt though (weird huh?). Any idea about this issue is welcomed.
It would be great if you could take some tests and review my PR above to see it is the best solution or not. Because currently i'm struggling with this issue and I wonder if other people also faced it too (like me).
Thanks for your comments.

**Comment by pedrobaeza** [comment]
PR merged.
