### ISSUE TITLE
[11] Add this repo on odoo apps

### ISSUE THREAD

**Issue by fmdl** [OCA/reporting-engine#190]
Dear @pedrobaeza 

It is possible to add this repo in V11 in Odoo Apps Store ?
https://apps.odoo.com/apps/dashboard/repos

Tanks

**Comment by naglis** [comment]
@fmdl, AFAICT the addons which have been migrated to V11 are available on the App Store, eg. [report_fillpdf](https://www.odoo.com/apps/modules/11.0/report_fillpdf/), [report_qweb_parameter](https://www.odoo.com/apps/modules/11.0/report_qweb_parameter/), [report_xlsx](https://www.odoo.com/apps/modules/11.0/report_xlsx/), etc.

**Comment by pedrobaeza** [comment]
I added the yesterday. Thanks for the follow-up.
