### ISSUE TITLE
Bi_SQL_Editor

### ISSUE THREAD

**Issue by indhutech55** [OCA/reporting-engine#196]
Once I created bi view and I have checked with graph and pivot views with the organized data,I can't able to reset it to draft again.

It shows error as,

Cannot rename/delete fields that are still present in views:
Fields: x_bve.analysisofdispatch.x_agent_id, x_bve.analysisofdispatch.x_city, x_bve.analysisofdispatch.x_company_id, x_bve.analysisofdispatch.x_country_id, x_bve.analysisofdispatch.x_date_done, x_bve.analysisofdispatch.x_del_categ, x_bve.analysisofdispatch.x_origin, x_bve.analysisofdispatch.x_partner_id, x_bve.analysisofdispatch.x_picking_type_id, x_bve.analysisofdispatch.x_sale_order_id, x_bve.analysisofdispatch.x_state_id, x_bve.analysisofdispatch.x_street
View: Graph Analysis

Kindly looks on this.

**Comment by asoral** [comment]
Even I am getting the same error. Moreover, I cant "-u all" my DB anymore with a sql view created.

**Comment by JordiBForgeFlow** [comment]
What version?

**Comment by indhutech55** [comment]
Version 10.

**Comment by asoral** [comment]
Me too... Version 10.

**Comment by legalsylvain** [comment]
Hi the module bi_sql_editor is not ported in version v10.

You can test and review the code of this PR https://github.com/OCA/reporting-engine/pull/206

kind regards.
