### ISSUE TITLE
Use PDF watermark in odoo 11

### ISSUE THREAD

**Issue by bjr-htb** [OCA/reporting-engine#205]
Hello everyone,

I'm trying to use this module in odoo 11, by overriding render_qweb_pdf method.
This a part of the code:
  res = super(IrActionsReport, self).render_qweb_pdf(docids, data=data)
........................................
               byte_list = bytearray()
                for item in res:
                    byte_list.append(int(item))
                for page in PdfFileReader(BytesIO(byte_list)).pages:
                    watermark_page = pdf.addBlankPage(
                        page.mediaBox.getWidth(), page.mediaBox.getHeight()
                    )
                     watermark_page.mergePage(pdf_watermark.getPage(0))
                     watermark_page.mergePage(page)
                 pdf_content = BytesIO()
                 pdf.write(pdf_content)
 
When I try to print report I get this issue:

byte_list.append(int(item))
ValueError: invalid literal for int() with base 10: b'%PDF-1.3\n1 0 obj\n<<\n/Type /Pages\n/Kids [ 3 0 R ]\n/Count 1\n>>\nendobj\n2 0 obj\n<<\n/Producer (PyPDF2)\n>>\nendobj\n3 0 obj\n<<\n/Annots 5 0 R\n/Parent 1 0 R\n/Resources 7 0 R\n/Contents 29 0 R

Can you help me?

Thanks

**Comment by pedrobaeza** [comment]
Sorry, but the module is not yet migrated, and this is for reporting issues with migrated modules, not for technical assistance.
