### ISSUE TITLE
receive data from wizard

### ISSUE THREAD

**Issue by onacer** [OCA/reporting-engine#209]
i can't get values of data from my wizard:

from openerp import models,fields,api
try:
    from openerp.addons.report_xlsx.report.report_xlsx import ReportXlsx
except ImportError:
    class ReportXlsx(object):
        def __init__(self, *args, **kwargs):
            pass

class excel_report_bilan(models.TransientModel):
    _name = 'account.excel.report'

    fiscalyear_id = fields.Many2one('account.fiscalyear', string="Fiscal Year")
    fiscalyear_id2 = fields.Many2one('account.fiscalyear', string="Fiscal Year 2 ")

 def print_xls_report(self, cr, uid, ids, context=None):
        if context is None:
            context = {}
        data = {}
        data['ids'] = context.get('active_ids', [])
        data['model'] = context.get('active_model', 'ir.ui.menu')
        data['form'] = self.read(cr, uid, ids, ['fiscalyear_id', 'fiscalyear_id2'], context=context)[0]
        return self.pool['report'].get_action(cr, uid, [], 'account_excel_report.report_bilan.xlsx', data=data, context=context)

class BilanReport(ReportXlsx):
    def generate_xlsx_report(self, workbook, data, partners):
        sheet = workbook.add_worksheet('Page1')
        sheet.set_paper(9)
        bold = workbook.add_format({'bold': True})
        merge_format = workbook.add_format({'bold': True,
                                             'size': 30,
                                             'align': 'center',
                                             'valign': 'vcenter',
                                            })
        merge_format2 = workbook.add_format({'bold': True,
                                            'size': 18,
                                            'align': 'center',
                                            'valign': 'vcenter',
                                            })
      
        sheet.merge_range('A8:G8', 'test', merge_format)
        sheet.merge_range('A11:G11', '(test)', merge_format2)
        sheet.write('A15', 'année :', bold)
        sheet.write('B15', data['form']['fiscalyear_id'][0], bold)
        workbook.close()

BilanReport('report.account_excel_report.report_bilan.xlsx', 'account.excel.report')

**# error key error form**
can someone help me?

**Comment by pedrobaeza** [comment]
This is for reporting issues on the modules of this repository, not for help on development questions. Please ask on the forums or mailing lists.

**Comment by onacer** [comment]
oki, thank you.
