### ISSUE TITLE
[V11] Error when report_xlsx and report_xml are installed. (Could not find client action 'web_settings_dashboard.main'.)

### ISSUE THREAD

**Issue by rogerv95** [OCA/reporting-engine#212]
When I have the two modules installed at the same time when I'm in developer mode and I go to the settings dashboard I get the next error:
`Could not find client action 'web_settings_dashboard.main'.`
And the settings dasboard doesn't load. If I uninstall any of them it works again. With any combination of modules works but if I have `report_xlsx` and `report_xml` installed at the same time this happens. I've checked the log files and anything appears on them no errors or warnings. I have alll the dependencies listed installed. If I leave developer mode with the two modules installed the settings dashboard works, it's only in developer mode and with the 2 modules installed.

**Comment by pedrobaeza** [comment]
Please check that the same happens on runbot: https://runbot.odoo-community.org/runbot/repo/github-com-oca-reporting-engine-143

**Comment by rogerv95** [comment]
@pedrobaeza  I've never used runbot, and I don't know what I exactly have to do, but I've logged in using quick connect under 11.0 and then (admin/admin) and I could already see the same happening. This is what you meant? Or what should I do?
If it was already happening there this means that is a known issue?

**Comment by pedrobaeza** [comment]
Yeah, that's it. Then we can consider this as confirmed.

**Comment by rogerv95** [comment]
Oh! I'm not used to come across an issue I really thought it would be my fault. Just to give you more information, I came across this when installing `l10n_es_facturae` and `l10n_es_mis_report` which I believe you are a contributor too.

**Comment by pedrobaeza** [comment]
@etobella you migrated report_xml. Did you experiment this?

**Comment by etobella** [comment]
Well, I see that the error does not happen when debug with assets is activated.

I will check where the error could be.

**Comment by etobella** [comment]
I fount the problem. A javascript definition was duplicated and it was giving problems.
I made a PR that solves the issue #213.

**Comment by pedrobaeza** [comment]
Fixed in #213
