### ISSUE TITLE
[11.0] report_qweb_element_page_visibility

### ISSUE THREAD

**Issue by vanbernaert** [OCA/reporting-engine#215]
small tweak to get the existing addon v10.0 'report_qweb_element_page_visibility' for v 10.0  working for v.11.0

views/layouts.xml

change 
`<template id="minimal_layout" inherit_id="report.minimal_layout">`
to
`<template id="minimal_layout" inherit_id="web.minimal_layout">`

**Comment by pedrobaeza** [comment]
Please make the PR: https://odoo-community.org/page/code

**Comment by vanbernaert** [comment]
the addon belongs to Agile Business Group. I can fork it, update for v11 and push to oca repository?
(im new here as odoo contributor)

**Comment by pedrobaeza** [comment]
Yes, you can contribute with the migration. This is an open community where everyone can do it. Please read migration guide, specifically the technical part for preserving commit history: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

**Comment by dipsshah42** [comment]
Its causing an issue while working with this module in v11.

@ssstofff and @pedrobaeza 
Issue is when printing report from listview for multiple records at once its duplicating/fumbling header and footer even in base's reports too.

Thanks,
Dipak

**Comment by pedrobaeza** [comment]
Closing while there's no PR for this.
