### ISSUE TITLE
Imposible instalar el módulo "report_xlsx" porqué hay una dependencia externa no resuelta: No module named xlsxwriter 

### ISSUE THREAD

**Issue by pedro2ms** [OCA/reporting-engine#219]
module: report_xlsx
version: 8.0

**Steps to reproduce**
- ... I try to install report_xlsx module but It's imposible because it says I don't have xlsxwriter installed, but it is installed.
I use:
pip install xlsxwriter method
Python says that is installed
But report_xlsx mosule says it not installed

I downloaded xlsxwriter tar package and run setup.py 
Python says that is installed
I probe xlsxwriter command´s to create a xlsx file. It works.
But when I try to install report_xlsx module it say module named xlsxwriter not installed again.
Please help me

**Current behavior**
Windows 10
Python 2.7.15
xlsxwriter 1.0.5
Odoo 8

**Expected behavior**

**Comment by pedrobaeza** [comment]
Sorry, but you haven't put correctly the dependency. Windows has these things. You have to copy to the Odoo directory.

**Comment by pedro2ms** [comment]
Thank you, could you be more especific please. Wich file I neeed to copy and where? 
 c:\python27\lib\site-packages\xlsxwriter-1.0.5-py2.7.egg copy to the odoo, addons directory
or c:\python27\scripts\vba_extract.py
