### ISSUE TITLE
[10.0] report_py3o generate invalid ODT when format_multiline_value() with '&' sign in text

### ISSUE THREAD

**Issue by alexis-via** [OCA/reporting-engine#220]
Scenario to reproduce the bug:
On a sale order, in the "note", write the text "tutu & tata". Then call a py3o report on that sale order that display the "note" field via the use of format_multiline_value(). You will get an invalid ODT file.

**Comment by jesusVMayor** [comment]
https://github.com/OCA/reporting-engine/pull/181 This PR fix it.

**Comment by alexis-via** [comment]
PR merged. Thank you very much @jesusVMayor
