### ISSUE TITLE
V10 - bi_view_editor

### ISSUE THREAD

**Issue by stevech091** [OCA/reporting-engine#222]
Hello, I have installed the V10 BI_view_editor but in the partner table I not found the tag category.
Is many2many fields manageble by this module?
Thanks

**Comment by astirpe** [comment]
@stevech091 many2many fields are not supported.
See https://github.com/OCA/reporting-engine/blob/10.0/bi_view_editor/models/ir_model.py#L22

**Comment by pedrobaeza** [comment]
@astirpe can this be included in the known issues / roadmap section?

**Comment by astirpe** [comment]
Yes, I think it should be clearly stated in the readme.

**Comment by pedrobaeza** [comment]
Would you? :angel:

**Comment by astirpe** [comment]
Here it is: https://github.com/OCA/reporting-engine/pull/224

**Comment by MiquelRForgeFlow** [comment]
Can be closed.
