### ISSUE TITLE
[11.0] Non qweb reports are not anymore supported. 

### ISSUE THREAD

**Issue by sergeiruzkiicode** [OCA/reporting-engine#223]
Try to use report_xlsx, after click frontend says me - _Non qweb reports are not anymore supported_

There was commint at 22.03.18 added this warning in /web/static/src/js/report/qwebactionmanager.js

**Comment by dek-odoo** [comment]
Hi @sergeiruzkiicode please make sure you are using latest code from [Report Engine](https://github.com/OCA/reporting-engine/blob/11.0).

As far as [this line](https://github.com/OCA/reporting-engine/blob/11.0/report_xlsx/static/src/js/report/qwebactionmanager.js#L11) exists, the error should not appear. You can also check, there is no error in console log to make sure the above line gets executed or it can be your custom JS having some error (try with debug=assets).

We add here a custom report type `xlsx`, so we also make it available to use through [from here](https://github.com/OCA/reporting-engine/blob/11.0/report_xlsx/static/src/js/report/qwebactionmanager.js#L11).

Hope this will help fix your issue !!

**Comment by pedrobaeza** [comment]
Indeed, this doesn't happen on latest code, so closing.

**Comment by kbirkbr** [comment]
@pedrobaeza , @dek-odoo, I used the latest build of `report_xlsx` module. But still getting the `Non qweb reports are not anymore supported`.

I tried to call the xlsx report from wizard like below.
def button_export_excel(self):
        print('Print')
        datas={}
        datas['form']=self.read()[0]
        return {'type': 'ir.actions.report',
                'report_name': 'kbir_partner_outstatnding_xlsx.partner_out_sts_xlsx',
                'datas': datas,
                'name': 'Partner Outstanding Report'
                }

It prints 'Print' statement in the terminal, that's all.
