### ISSUE TITLE
Reset to Draft

### ISSUE THREAD

**Issue by shbrguli** [OCA/reporting-engine#227]
Hi,

I dont know if nay of you have noticed that once the BI view is created and generated, it doesnot allow to reset to draft and generates the error 
![1](https://user-images.githubusercontent.com/41262348/42733469-40498b6e-884b-11e8-8b56-f8213bcd781f.png)
![1](https://user-images.githubusercontent.com/41262348/42733472-44a39420-884b-11e8-9992-8fc9922ce3fc.png)

**Comment by pedrobaeza** [comment]
Odoo version? Is it reproducible on runbot?

**Comment by shbrguli** [comment]
Well on run bot it does not show the access point of Custom BI views
![1](https://user-images.githubusercontent.com/41262348/42752229-abb2f7f8-8906-11e8-8522-2962e2b7c076.png)

**Comment by shbrguli** [comment]
I was wrking on odoo 10

**Comment by pedrobaeza** [comment]
I mean OCA runbot: https://runbot.odoo-community.org/runbot/repo/github-com-oca-reporting-engine-143

**Comment by shbrguli** [comment]
Let me check

**Comment by shbrguli** [comment]
Well on OCA run bot it is not showing any error

**Comment by pedrobaeza** [comment]
Then it's seems another module is choking with this one.

**Comment by shbrguli** [comment]
The error that I have mentioned in above threads, it seems that it is not deleting the columns in views once it has been created. But on run bot it is working fine.

**Comment by shbrguli** [comment]
How ever thanks Mr Pedrobaeza for your help

**Comment by pedrobaeza** [comment]
Check permissions on your DB and user and try on a fresh DB. I close this issue meanwhile as it seems to not be something in the module.
