### ISSUE TITLE
PDF merging process

### ISSUE THREAD

**Issue by grindtildeath** [OCA/reporting-engine#241]
I open this issue here to discuss how PDFs should be merged in odoo using OCA modules.

The issue stems from this commit in the migration of l10n_payment_slip module : https://github.com/OCA/l10n-switzerland/pull/373/commits/0e06d3cbcf228472a32eda71e2b73e1ed286f54c

As this module uses `reportlab-pdf` instead of `qweb-pdf` as report_type, we generate each PDF report in a temporary file, and merge these afterwards using one of these two methods (depending on `res.company` configuration) :
```
    def merge_pdf_in_memory(self, docs):
        merger = PyPDF2.PdfFileMerger()
        for doc in docs:
            merger.append(doc)
        buff = io.BytesIO()
        try:
            # The writer close the reader file here
            merger.write(buff)
            return buff.getvalue()
        except IOError:
            raise
        finally:
            buff.close()

    def merge_pdf_on_disk(self, docs):
        merger = PyPDF2.PdfFileMerger()
        for doc in docs:
            merger.append(doc)
        buff, buff_path = tempfile.mkstemp(
            suffix='.pdf',
            prefix='credit_control_slip_merged')
        try:
            buff = os.fdopen(buff, 'w+b')
            # The writer close the reader file here
            buff.seek(0)
            merger.write(buff)
            buff.seek(0)
            return buff_path
        except IOError:
            raise
        finally:
            buff.close()
```
This was done to allow a merge on disk instead of on memory to prevent shortage in case there are lots of reports to merge.
However, as stated in the commit above, Odoo uses such a machinery in `_post_pdf` (https://github.com/odoo/odoo/blob/11.0/odoo/addons/base/ir/ir_actions_report.py#L548) to merge in memory as long as you're not reloading only one report from an attachment.

Should we have a module here overwriting `_post_pdf` to allow the use of one of the merge policy above ? Did anyone face significant memory shortage on this code ?

cc @simahawk @yvaucher

**Comment by yvaucher** [comment]
Thanks for opening that issue, indeed merge_pdf_on_disk was created long ago, IIRC in version 7.0 by @nbessi to be able to generate hundred of reports at once.

Current code in Odoo core doesn't allow a proper overriding of this function we should propose a hook to define our own merge policy. This shouldn't be too hard to move that part in a separate method in ir_actions_report.py.

Then with this patch on Odoo, a small module that implement the merge policy can definitely go into that repository.

**Comment by simahawk** [comment]
and since we are heading to v12 might be the right time to propose a change for the hook?
