### ISSUE TITLE
Error: undefined

### ISSUE THREAD

**Issue by elitumgroup** [OCA/reporting-engine#255]
Error:
![error de odoo - origen](https://user-images.githubusercontent.com/38440711/48506700-06752600-e818-11e8-8e2b-1ac585c352da.png)
![error de odoo](https://user-images.githubusercontent.com/38440711/48506704-0a08ad00-e818-11e8-83a0-5a7c91a24802.png)

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with OCA modules hosted here.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.
