### ISSUE TITLE
10.0 Sales Sum

### ISSUE THREAD

**Issue by lauracvilla-zz** [OCA/reporting-engine#261]
Hi,
I am using BI View Editor to see my sales. I am doing a report of sale by brand, but I want to see my real sales, for example my sales are 100$ and I have a refund by 20$, my real sale is 80$. But my report looks:

Brand   1                     120$
Customer Invoice        100$
Customer Refund          20$

Because I create the report by on invoice line, type Customer Invoice and Customer Refund.

How can I create a negative value for Customer refund and it will sum the correct value? because I'am not sold 120$ and that would be a problem to me.

Or there is a better way to create this report? Thanks for your help.

**Comment by pedrobaeza** [comment]
This is out of the scope of the issue tracker, because this is for notifying bugs, but a quick trick over this: there's a field called `amount_signed` or similar for this. If you have more doubts, you should do them on the forums or mailing lists.

**Comment by lauracvilla-zz** [comment]
Thanks for your help @pedrobaeza  I'ḿ new and learning how to use the tools and community platform.
