### ISSUE TITLE
 I can not enable the exportart xml option

### ISSUE THREAD

**Issue by david270291** [OCA/reporting-engine#266]
In the readme file it indicates: "You will be able to download XML reports from the Print menu found on form and list views" 
I do not see that option, as I can enable it.
I have all the dependencies installed. The views appear:
- ir.actions.report
- report_xml.assets_backend
I'm very lost where can I start looking?
thanks

**Comment by pedrobaeza** [comment]
That line should be removed, as it's not that way. I will do it immediately. As I already told you in #262, the module is only a base for other modules to use this engine, and that modules add the proper entries. Look for the FacturaE module instructions to see how to access them.

**Comment by pedrobaeza** [comment]
Fixed in https://github.com/OCA/reporting-engine/commit/4ab706f93c224c5d4718d61e5f04778de4b08896

**Comment by david270291** [comment]
In this link indicates the same as in the readme of the web, I do not see any option, as indicated in the readme "if you refer me to the same document that does not indicate the solution, you do not help me to find a solution.
I do not know if you mean that I should post the comment in another thread or I do not know.
But so you are not helping me

**Comment by pedrobaeza** [comment]
The problem you have is not with this module, but with l10n_es_facturae, and there are clear instructions there:

https://github.com/OCA/l10n-spain/blob/11.0/l10n_es_facturae/README.rst#uso

The absurd is to put here an issue for that.

**Comment by david270291** [comment]
Not everyone, we are experts in the field, I think you can understand that there are beginners like me, who want to learn.
In all this time you have invested in answering 3 comments and calling my ticket absurd and you could have invested in a more contructive way

**Comment by pedrobaeza** [comment]
David, the question is to focus what is your problem. I'm answering everything you put including private emails redirecting to the proper place, and even removing the confusing text for not being confusing anymore, but the rest is unclear on what is your problem.
