### ISSUE TITLE
New Report Engine (xlsx import/export/report), seek for advice how to contribute

### ISSUE THREAD

**Issue by kittiu** [OCA/reporting-engine#268]
I have a module to produce excel report (as well as ability to import). The way it works will be a bit different from what already exists in OCA. so I would like to sound check,
1. Whether this module should be in OCA
2. Are there anything done in similar fashion yet
3. Which repository it should be in (this is not just report but also import and export)

Use case for this addon,

**Case 1: used to create excel report**
Report can be generated from any model or view.

**Case 2: used as import / export excel tools for any document model**
For example, in any active document (any model), to do fast data entry by using excel,
- Click export document as excel
- Open excel which now show all header and lines of that document.
- User edit / delete / add lines in the excel file.
- Click to import excel back, all new information will get updated to the document as per excel (by delete delete then add)

**Technically, we need to create 2 things**
1. Excel Template (we can do formatting, labeling, add formalas or anything as per normal excel).
2. Descriptor (we now keep in ir.attachment to be together with excel template file), in dictionary format, for both __IMPORT__ and __EXPORT__

For example, the excel template can be like this,
![00218](https://user-images.githubusercontent.com/1973598/51031808-45cdb200-15d0-11e9-84d3-dc57d3947ece.png)
And the ir.attachment which hold both template and its descriptor can be like this.
![00219](https://user-images.githubusercontent.com/1973598/51031839-5d0c9f80-15d0-11e9-8d2c-c4f044073f16.png)
![00220](https://user-images.githubusercontent.com/1973598/51031844-6433ad80-15d0-11e9-841b-fc4c92a0ba08.png)

As you can see, the excel template's formatting will stays as untouched. The descriptor will tell system how data will be filled into each cell, and how to display it (can use orm capability). And we also have some more markup, i..e, to format number, datetime, bold, color, or insert line as subtotal / total lines. There are more things it can do with similar method, i..e, to transform data from 1 sheet using panda library and lay it down to another sheet.

At first we also looking to report_xlsx, although it make coding easy, it still quite time consuming considering we have to do dozens of reports. This make things much faster with predesigned templates and configurable dictionary for both __IMPORT__ / __EXPORT__.

Also, we got requirement about excel import, also in dozens of windows. And the logic of export and report are quite the same, that's why all are in the same package.

**Note:** Not all kind of reports can be achieved by this tools, imagine report with many level of subtotals, report_xlsx will be better, as we can code anything.

**Comment by pedrobaeza** [comment]
There's already `report_xlsx`, so please elaborate.

**Comment by kittiu** [comment]
moved to #273
