### ISSUE TITLE
New addons "xlsx_imexprt" (allow import, export, reporting), seek for advice.

### ISSUE THREAD

**Issue by kittiu** [OCA/reporting-engine#273]
Hi, based on previous issue #268 . I have migrate the module from v8 now to v11 now. In brief here is how it works,

- It works as pre-build functions and wizards for further export data with excel.
- User will define template (xlsx.template, as dictionary), and it will generate excel as output
- Instead of using code to create an excel file, it write data in to predefined xlsx.template without touching the format or formulas in excel.
- We can also use it to export out excel from an object, and import back the file to object.

To test following sample, you can install xlsx_imexprt, xlsx_imexrpt_sample, 
https://github.com/ecosoft-odoo/reporting-engine/tree/11-xlsx_imexrpt

**Sample: creating sales order report**

We first create report template (template excel with any format) and define how data will be mapped to excel cells in dictionary __EXPORT__ section in xlsx.template

![00335](https://user-images.githubusercontent.com/1973598/52681077-3b0a9200-2f6d-11e9-8715-f366194f8a1f.png)
By little coding, we create menu and inherit wizard, add some search criteria logic, and we can product the report as following,

![00336](https://user-images.githubusercontent.com/1973598/52681157-7efd9700-2f6d-11e9-8637-a347db352584.png)

![00338](https://user-images.githubusercontent.com/1973598/52681282-e287c480-2f6d-11e9-9e5a-634d3d4b4df4.png)

**Sample: use it as Export/Import to a sales order**

Similarly, create report template, this time with both __EXPORT__ and __IMPORT__ section.

![00339](https://user-images.githubusercontent.com/1973598/52681511-a5700200-2f6e-11e9-8358-1b1967e26c00.png)

Then on Sales Order, we can have menu to Import and Export this Sales Order in excel.

![00340](https://user-images.githubusercontent.com/1973598/52681672-3f37af00-2f6f-11e9-8169-d050f892c18f.png)
![00341](https://user-images.githubusercontent.com/1973598/52681675-42329f80-2f6f-11e9-9114-1538a1c604b3.png)
![00342](https://user-images.githubusercontent.com/1973598/52681679-46f75380-2f6f-11e9-97e8-2ef87f0fab81.png)

**Comment by kittiu** [comment]
I would love to have suggestion, whether this kind of module can be in OCA repo, and which repo is sutible. (also the naming of this module).

**Comment by NL66278** [comment]
I would think it should got to server-tools, here are a lot of modules for connecting Odoo with external data. There is also the connector repository, but that is based around a very particular framework. I would call your module excel_import_export as that seems to best encompass what your module does. It is definitely more encompassing then reporting.

**Comment by elicoidal** [comment]
@kittiu thanks for the proposal. Interesting feature that can be helpful for functional end users.
One question: for the order lines, somehow you should indicate the cell of the first row and indicates that this is a loop over multiple lines. It is not clear in your example above.

**Comment by kittiu** [comment]
@elicoidal , the order_line is one2many so it will always be looping to multiple lines. But we can limit the number of rows as to, i.e., 'order_line[5]' means 5 lines only.
There are also taging allow user to do something like, subtotal, total for last row, group by...

**Comment by kittiu** [comment]
@NL66278 Thank you for your suggestion. Yes, may be server-tools is better.

**Comment by kittiu** [comment]
Start working on PR https://github.com/OCA/server-tools/pull/1512

**Comment by kittiu** [comment]
Close as redundant.
