### ISSUE TITLE
'report_qweb_element_page_visibility' v11

### ISSUE THREAD

**Issue by AhmadAdel96** [OCA/reporting-engine#277]
How are you able to make the report_qweb_element_page_visibility work on v11 of Odoo, i did try to change the report to web in layout.xml but it did not work, and while installing it give me the following error: 
You try to install module 'report_qweb_element_page_visibility' that depends on module 'report'.
But the latter module is not available in your system.

**Comment by pedrobaeza** [comment]
Module is being migrated in #186
