### ISSUE TITLE
bi_sql_editor aggregator operator for fields

### ISSUE THREAD

**Issue by agb80** [OCA/reporting-engine#291]
We have being worked on an analysis for a customer who would like to get a table that displays the percentage of the objectives achieved by salesman. 

We go for create an bi_sql_editor view because seems really a simple request, but when we give him the pivot table he start to complain that aggregation on percentage columns is wrong because is summing percentages instead of averages. For solve the need we migrate the view from this module to custom module.

Now I was thinking that if we could create this kind of queries from graphic interface as  possible with bi_sql_editor our life will be simpler. I'm leaving this here to see if any one have a similar request and can give us a starting point as for me seems is not a trivial task as on mainstream there is no possible to indicate aggregate operator on custom fields.

**Comment by CasVissers-360ERP** [comment]
I think this would be a great addition as well. I think we would need to be able to set the group_operator voor measures. For example group_operator='avg'. 

Don't know if this is a planned update for the module.

**Comment by CasVissers-360ERP** [comment]
See #344
