### ISSUE TITLE
NEW MODULE: report_branding

### ISSUE THREAD

**Issue by agent-z28** [OCA/reporting-engine#297]
We have an module, where we can use pdftk to brand any report with an "branding pdf".
The advantage is, that we can make the report look 100% as the client wants it.
The pdf layer can be ontop or behind the main one.

**Comment by pedrobaeza** [comment]
Similar to https://github.com/OCA/reporting-engine/tree/11.0/report_qweb_pdf_watermark

**Comment by agent-z28** [comment]
Wow respect the OCA has more then most people know!
Its somehow hard to find!
How can we improve this!
We should tag all modules?

**Comment by agent-z28** [comment]
We have some useful updates for this.
We can have default branding, diffrent versions, assigned to diffrent reports...
maybe i will PR

**Comment by pedrobaeza** [comment]
OK, great
