### ISSUE TITLE
[11.0] Error: undefined when priting xlsx reports (using account_financial_report)

### ISSUE THREAD

**Issue by mohssinodoo** [OCA/reporting-engine#302]
Hello Community,
I got this error when i try to print an xlsx , i'm using an official OCA module account_financial_report

![xlsx_issue](https://user-images.githubusercontent.com/48224883/60114551-f2a97f00-976b-11e9-9aad-d89d9b341022.gif)

**Comment by pedrobaeza** [comment]
Sorry, but the error is not very clear, but you should recreate it on runbot, and the proper place should be OCA/account-financial-reporting.

**Comment by mohssinodoo** [comment]
Hello @pedrobaeza , Thanks for the feedback, i didn't explain well this issue it's actually the same as this closed issue https://github.com/OCA/reporting-engine/issues/255 , I'm developing a customized module using report_xlsx , I've used account_financial_report just as an example , when printing an xlsx report and try to navigate or access to another module i get the undefined error , this issue is not reproducible on runbot or on community version.

**Comment by pedrobaeza** [comment]
Then the problem is due to enterprise interface, and thus there's no direct support unless you find a way to compatibilize both interfaces (community and enterprise).

**Comment by quenna999** [comment]
hi there,we are looking for apple enterprise account due to company urgent project.can pay for that .
fanboer@gmail.com
skype:live:fanboer
plz kindly contact us if u can help,thanks

**Comment by quenna999** [comment]
Hello community,
we are looking for apple enterprise account,would like to pay 10000 usd or more for one account.plz kindly contact us at any time.for more details plz visit our website:http://0818yst.com/index.asp
fanboer@gmail.com
skype:live:fanboer
