### ISSUE TITLE
Bi view editor

### ISSUE THREAD

**Issue by ljacobo** [OCA/reporting-engine#308]
Hi, im using Odoo v11 and recently installed the bi view editor module, but when i try to create a new one i have the error "Uncaught Error: QWeb2: Template 'bi_view_editor.Frame' not found".

Any help?

thnks..

**Comment by astirpe** [comment]
I cannot reproduce the error. How did you deploy/install the module?

**Comment by acysos** [comment]
I get the same error. I have update the module from terminal and it's solved
