### ISSUE TITLE
Bi View editor error when updating Odoo from Github

### ISSUE THREAD

**Issue by bennals** [OCA/reporting-engine#316]
I've been using Bi View Editor for a while now and have encountered an error related to it when I update the Odoo source code from github.  The error log is below.

I can work around it by going into Dashboards->Custom BI Views and resetting all of the created views to draft, after which the Odoo update completes normally.  I gather this removes the custom objects that are created by the 'Generate BI View' process.

If I forget to do that, I get the error below and then can't connect to the server via the gui (Internal Server Error 500) to go in and reset the views to draft, so I have to restore from a backup and start again.

I can't test this on the OCA runbot obviously as it requires server admin access.  

Is this expected behaviour or should a fetch and reset via Github be able to deal with the custom objects created by the BI View Editor?

2019-08-11 23:22:13,772 27363 ERROR production odoo.sql_db: bad query: b'ALTER TABLE "x_bve_posreportforvendorswsprice" ADD COLUMN "create_uid" int4'
ERROR: "x_bve_posreportforvendorswsprice" is not a table, composite type, or foreign table

2019-08-11 23:22:13,778 27363 WARNING production odoo.modules.loading: Transient module states were reset
2019-08-11 23:22:13,780 27363 ERROR production odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/odoo/odoo-server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/odoo-server/odoo/modules/loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/odoo-server/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/odoo-server/odoo/modules/loading.py", line 153, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/home/odoo/odoo-server/odoo/modules/registry.py", line 306, in init_models
    model._auto_init()
  File "/home/odoo/odoo-server/odoo/models.py", line 2220, in _auto_init
    new = field.update_db(self, columns)
  File "/home/odoo/odoo-server/odoo/fields.py", line 1953, in update_db
    return super(Many2one, self).update_db(model, columns)
  File "/home/odoo/odoo-server/odoo/fields.py", line 848, in update_db
    self.update_db_column(model, column)
  File "/home/odoo/odoo-server/odoo/fields.py", line 1956, in update_db_column
    super(Many2one, self).update_db_column(model, column)
  File "/home/odoo/odoo-server/odoo/fields.py", line 862, in update_db_column
    sql.create_column(model._cr, model._table, self.name, self.column_type[1], self.string)
  File "/home/odoo/odoo-server/odoo/tools/sql.py", line 77, in create_column
    cr.execute('ALTER TABLE "{}" ADD COLUMN "{}" {}'.format(tablename, columnname, columntype))
  File "/home/odoo/odoo-server/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/odoo-server/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: "x_bve_posreportforvendorswsprice" is not a table, composite type, or foreign table

**Comment by pedrobaeza** [comment]
I have found this error only while migrating between major versions, but it's something to address.

@astirpe can you please check this?

**Comment by astirpe** [comment]
Looking at the stack trace above:

> 
> File "/home/odoo/odoo-server/odoo/modules/registry.py", line 306, in init_models
> model._auto_init()
> File "/home/odoo/odoo-server/odoo/models.py", line 2220, in _auto_init
> new = field.update_db(self, columns)

it seems that this [monkey patch](https://github.com/OCA/reporting-engine/blob/11.0/bi_view_editor/models/models.py#L21-L32) is not executed for some reasons. That monkey patch is meant to bypass the creation of "magic" fields (eg.: `create_uid`, like in in this case) on the `x_bve_posreportforvendorswsprice` that is a postgres view (and thus "is not a table, composite type, or foreign table...").

Unfortunately at the moment I don't have any solution, other than the already existing monkey patch. 
Does the update of the core of Odoo by Github somehow make the `_auto_init`, defined in "`/home/odoo/odoo-server/odoo/models.py`", taking over the monkey patch?

@pedrobaeza did you face any similar issue in the past or do you have any insight to solve this?

**Comment by bennals** [comment]
thanks for the responses.  I don't know if it makes any difference but I should have mentioned above that the same error occurs if I do '-u base', rather than '-u all'.

Thank you for the wonderful modules in any case.

**Comment by HviorForgeFlow** [comment]
I think you can solve this error adding bi_view_editor to options.server_wide_modules on odoo config file.

**Comment by bennals** [comment]
ok, thank you @hveficent , I will give that a try.

**Comment by astirpe** [comment]
@bennals did the proposed fix (https://github.com/OCA/reporting-engine/issues/316#issuecomment-520386897) work for you?

**Comment by bennals** [comment]
@astirpe @hveficent 
Apologies for the delayed response.  Yes, it does appear to have solved the problem.  Thank you both for your help.  Perhaps this requirement could be added to the readme?

**Comment by HviorForgeFlow** [comment]
@bennals can you add it to the readme? Thanks

**Comment by astirpe** [comment]
Already added while porting to V12: https://github.com/OCA/reporting-engine/pull/293/commits/66d8cd39acf5868d14bb0c7b26315e957896e7b0

That commit should be backported to previous versions.
