### ISSUE TITLE
[8.0] report_custom_filename: Module can't be installed

### ISSUE THREAD

**Issue by Whytehorse** [OCA/reporting-engine#32]
I donwloaded this module and tried to import it into Odoo 8 stable nightly build and it gives an error with no description. The server logs have this error:
ERROR production openerp.addons.base.ir.ir_ui_view: 
Field `download_filename` does not exist
Error context:
View `ir.actions.report.xml form`
[view_id: 1085, xml_id: n/a, model: ir.actions.report.xml, parent_id: 7]

**Comment by pedrobaeza** [comment]
It seems you are not restarting your server before upgrading/installing the module. Anyway, it's not a issue, because it's installed perfectly.

**Comment by Whytehorse** [comment]
I restarted the server and your response has nothing to do with the issue and it's not resolved at all so please re-open it. Thanks.

**Comment by pedrobaeza** [comment]
Sorry, the problem is not reproducible in all the installations we have, including runbot, so you have to check your local installation. Please try here in runbot to see perfectly working: https://runbot.odoo-community.org/runbot/repo/github-com-oca-reporting-engine-143

**Comment by Whytehorse** [comment]
Can you provide a link to the working version and describe how it was installed? The version I have is from the github zip download and also from the odoo apps website. I'm able to install other addons just fine by downloading the zip file and clicking "Import Module" but most of the OCA modules have field or module not found errors.

**Comment by pedrobaeza** [comment]
"Import module" never works for this kind of modules. They're just for data modules (like themes). You should download and put in one of the addons folder you define in your server.

**Comment by Whytehorse** [comment]
I fixed this by getting the permissions right on the module. turns out is need root owner, root group, and 755 permissions
