### ISSUE TITLE
report_xlsx: Can not pass context values to xlsx reports

### ISSUE THREAD

**Issue by jffernandez** [OCA/reporting-engine#326]
The context is overridden with this one with that only key, is this intended?
https://github.com/OCA/reporting-engine/blob/79166e71122b1691f67a7820bc95fa38fd2e2dcc/report_xlsx/models/ir_report.py#L19-L21
Because I need to pass some value in context and read it from report, had I miss something?
I can submit a patch in case it's a bug.

**Comment by pedrobaeza** [comment]
Isn't #259 for the same?

**Comment by jffernandez** [comment]
Sure! I only looked on issues, my bad, sorry!
Anyway, I think that the JavaScript ActionManager needs to be patched too, because is not propagating the context from the action (but I'm not sure if it has to, that worked for me)
Please, feel free to close the issue if not needed.
Thank you!

**Comment by pedrobaeza** [comment]
Please try that PR to check if works and review it :smiley:
