### ISSUE TITLE
PDF function cannot work in Odoo.sh

### ISSUE THREAD

**Issue by captivea-fpo** [OCA/reporting-engine#328]
Hello, 

For your information, Odoo support refuse to install "libreoffice" package on Odoo.sh. 
It means that cannot use PDF functionnality.

Have you a other solution for print PDF with Py3o engine ?

Regards,

**Comment by yostashiro** [comment]
@captivea-fpo We had a different response from the Odoo.sh support team just a couple of months ago.

> We've had this request before, libreoffice is already installed in your container image.
> 
> $ which libreoffice
> /usr/bin/libreoffice

Maybe you can check with them once again?

**Comment by captivea-fpo** [comment]
@yostashiro  Oh my god. I'm so sorry. I didn't verify that.
You are right, libreoffice are already installed.
Thanks you so much for this informations
