### ISSUE TITLE
This repo and report-print-send should be merged

### ISSUE THREAD

**Issue by clonedagain** [OCA/reporting-engine#33]
This repo was probably intended to contain reporting engines like `report_xls`, but now it contains utilities such as `report_custom_filename`.
The lines between this and https://github.com/OCA/report-print-send/ are fuzzy and there is not a lot of activity in either.
I propose they should be merged together.

**Comment by yvaucher** [comment]
report-print-send is precisely designed to include modules with interaction with printers.

I prefer it separated thought it could be under the same PSC.

**Comment by pedrobaeza** [comment]
Same for me, so I close the issue.
