### ISSUE TITLE
duplicate controller in report_xlsx_helper

### ISSUE THREAD

**Issue by sbidoul** [OCA/reporting-engine#336]
While working on #259 I noticed the controller in `report_xlsx_helper` seems to be a duplicate of the one in `report_xslx`. Is this by accident, or is there a reason for this that I overlook?

**Comment by luc-demeyer** [comment]
I need to be able to process the context in order to allow 'dynamic' (hence not predefined) xlsx reports.
Now that your patch allows to pass the context I can review this code or move the capability of dynamic xlsx reports into report_xlxs.
