### ISSUE TITLE
Repo is not registered on Transifex

### ISSUE THREAD

**Issue by clonedagain** [OCA/reporting-engine#34]
To the best of my knowledge, this repo is not translatable on Transifex.
Can you please add it there?

**Comment by pedrobaeza** [comment]
Nobody in the PSC or community has set the lines in .travis.yml to do it. Would you mind to do it? Look at the template for that: https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml#L35

**Comment by pedrobaeza** [comment]
Activated also in 9.0 in https://github.com/OCA/reporting-engine/commit/fbed7cef582083c3f07406f7ea4bd9d623c10f0b, so I close this one.
