### ISSUE TITLE
[RFC] Generate report to plain text format

### ISSUE THREAD

**Issue by dreispt** [OCA/reporting-engine#341]
Use QWeb templates to generate plain text files, usually CSVs.
This would be something similar to report_xml, but with some post processing to have a friendly processing of Tabs and Newlines.

**Comment by pedrobaeza** [comment]
You have https://odoo-community.org/shop/product/base-report-csv-4653, and I remember something from @alexis-via for TXT.

**Comment by patel1008b** [comment]
@dreispt 

https://github.com/OCA/reporting-engine/tree/10.0/report_qweb_txt

https://github.com/akretion/dilicom/tree/10.0/purchase_dilicom_csv

**Comment by etobella** [comment]
report_csv module could probably solve your problem:
#272 - Approved
#305 - Migration to 12.0

**Comment by dreispt** [comment]
Thank you! 
report_csv requires coding, and aI would like to have something that is template driven.
report_qweb_txt is QWeb based and look like what I was looking for!
