### ISSUE TITLE
[BUG] report_qweb_element_page_visibility : class "last-page" not show every last page of document

### ISSUE THREAD

**Issue by kongrattapong** [OCA/reporting-engine#349]
In Odoo V.12
Step: 
   - Create 2 invoices and print invoices
   - I got 2 report (every report have only 1 page) 
but footer show only last page (show only 1 footer), it's should be show footer every last page of document

**Comment by pedrobaeza** [comment]
That's not supported AFAIK.

**Comment by Abranes** [comment]
We have the same problem. In 12.0 the footer show only in the last page (2 invoices, 1 footer) but in 10.0 the footer show in the last page of every report (2 invoices, 2 footers).
