### ISSUE TITLE
[11.0] report_xls: Block UI during xls file building

### ISSUE THREAD

**Issue by dmsergio** [OCA/reporting-engine#381]
Hello,

I'm not sure if this is a issue or not. So, when I launch any process to export a xls report file, the Odoo UI doesn't block. Exists any way to block UI during the file build process is running?

**Comment by hdangelo217** [comment]
Fixed on PR #287 but still open.

**Comment by dmsergio** [comment]
Thanks for your answer @hdangelo217, I'm going to test your PR and I will give you feedback.
