### ISSUE TITLE
[RFC] kpi_dashboard vs web_dasboard_tile : take into account context

### ISSUE THREAD

**Issue by legalsylvain** [OCA/reporting-engine#415]
Hi all,

In previous version of Odoo, I was using ``web_dashboard_tile`` that generates tiles with computed values. Following [this discussion](https://github.com/OCA/reporting-engine/pull/387#issuecomment-614242900), we decided to abandon ``web_dashboard_tile``, and focus the work on ``kpi_dashboard``, that has more features.  

However, ``web_dashboard_tile`` compute values on the fly, and ``kpi_dashboard`` stores values. So ``kpi_dashboard`` is faster, but doesn't take into account the context. In a multi company context, if a kpi is "Sum of the opened invoices to pay", ``kpi_dashboard`` will display a unique global values to all users. It is expected to display a value depending on the context of the user. (display only the opened invoices of the current company).

How do see I could improve the ``kpi_dashboard`` module to take into account the context ? 

I was thinking to add a boolean ``compute_on_the_fly``, unchecked by default, on the ``kpi.kpi`` model. 
- if unchecked : existing behaviour.
- if checked : no cron is generated, and the value is computed on the fly. (slower, no bus, but take into account context).

What do you think ? 

Thanks !

CC : original author of ``kpi_dashboard`` : @etobella 
reviewers of the ``kpi_dashbaord`` module : @AaronHForgeFlow, @ivantodorovich, @andreampiovesana, @LoisRForgeFlow, @AdriaGForgeFlow. 
reviewers / coauthors of the ``web_dashboard_tile`` module : @steigendit, @zaoral, @OSguard, @ivantodorovich, @pedrobaeza

**Comment by ivantodorovich** [comment]
I haven't dug into that module yet, but maybe you could create one kpi per
company:
"Sum of the opened invoices to pay (company A)"
"Sum of the opened invoices to pay (company B)"
etc..

That way you don't need to sacrifice performance

If you go for this approach, I think it would make sense to add an optional
company_id field, with a corresponding ir.rule, in kpi.kpi.

**Comment by etobella** [comment]
Well, I think it is good to use this kind of new behavior, even in the base module, so it is good for me.

**Comment by pedrobaeza** [comment]
The problem I see is that there's no historic storage of previous values, and proper visualization of them. For a kpi you want to see its trend, not only previous and current value.

**Comment by etobella** [comment]
Well, trends can be stored, and there is a way to show trends. Also, in my experience, it has no sense to store the data. Let me show an example:

In my company we check the sale.orders by the arrival of the customer, so, there is a small difference in the value of the previous month, as it can be made several days later. So, it has no sense to check that yesterday, June amount was 10.000 and today is 11.000 as the real value is 11.000.
On accounting, you might need to make a revision move if there was some mistake that needs to be applied some days on the past, so, the values might change.

Currently, KPI is allowed to store trends (with graphs) and current value and previous value, that allows to define the current value and the growth

**Comment by pedrobaeza** [comment]
KPI in the most strict meaning is only one value, not several, and that value can't be recomputed in the future due to specific data state. For example, open tasks with more than 5 days of delay. This KPI can't be computed with the same result in the future, as it depends on the state of the task (that now can be closed). And anyway you shouldn't be forced to recompute each time the same historic value if you want to see it, although the graph "allows" you more or less to do it.

That's why an automatic saving of historic data link to date/datetime should be done (similar to product.price.history historization), and provide tools for viewing that historic data. This is the minimum to ask in a KPI system.

**Comment by etobella** [comment]
Well, I think that both points of view are legit, let me make a PR trying to solve all the options :wink:

**Comment by etobella** [comment]
@legalsylvain This issue can be closed
