### ISSUE TITLE
py3o not working

### ISSUE THREAD

**Issue by abrigard** [OCA/reporting-engine#419]
I installed py3o successfully but when I try to print the sample report in Users, it pops up an error with no details:

![imagen](https://user-images.githubusercontent.com/9010905/88335579-28b38c80-ccf9-11ea-8a67-9e1e09bb21e6.png)

In the log the only hint is this one:
`2020-07-23 20:25:10,346 28004 WARNING odoo12-pruebas odoo.http: <function addons.web.controllers.main.report_download> returns an invalid response type for an http request 
2020-07-23 20:25:10,347 28004 INFO odoo12-pruebas werkzeug: 127.0.0.1 - - [23/Jul/2020 20:25:10] "POST /report/download HTTP/1.1" 204 - 3 0.001 0.003`

**Comment by legalsylvain** [comment]
did you reproduced the bug on runbot ?

**Comment by abrigard** [comment]
I do not know how to do it. I will try and get back with the results.

**Comment by abrigard** [comment]
Hi, The same py3o report in the OCA runbot works fine.

I installed py3o Reporting Engine in an empty database. Then, I executed the py3o Demo report in this empty database and had the same result.

I have found that the py3o controller is not called when I execute the py3o report. The reported error is generated by line 1629 in `web/controllers/main.py` in the function `report_routes` in the `Class ReportController` when the converted is not html, pdf, or text.

**Comment by abrigard** [comment]
I installed py3o Reporting Engine in an empty database. Then I executed the py3o Demo report in this empty database and had the same result.

**Comment by abrigard** [comment]
Solved!!!
There was a module with controllers outside the controllers directory. I moved those files to the controllers directory and it worked ok.

**Comment by abrigard** [comment]
I thought it was solved, but it was because I was not importing the controller that generates an Excel file with a report. It seems py3o is having a conflict with this controller:

Does any body has a clue what is the problem?

```
from odoo import http
from odoo.http import request
from addons.web.controllers.main import content_disposition
import os

class urlConcentracionesReport(http.Controller):

    @http.route('/web/operaciones/concentracionReport', auth="user")
    def download_document(self, filename=None, **kwargs):
        f = open('/home/odoo/.tmp/'+filename, 'rb')
        filecontent = f.read()
        if not filecontent:
            return request.not_found()
        else:
            if not filename:
                filename = filename + '.xls'
            os.remove('/home/odoo/.tmp/'+filename)
            return request.make_response(filecontent,
                                             [('Content-Type', 'application/octet-stream'),
                                              ('Content-Disposition', content_disposition(filename))])
```

**Comment by abrigard** [comment]
I thought it was solved, but it was because I was not importing the controller that generates an Excel file with a report. It seems py3o is having a conflict with this controller:

Does any body has a clue what is the problem?

```
from odoo import http
from odoo.http import request
from addons.web.controllers.main import content_disposition
import os

class urlConcentracionesReport(http.Controller):

    @http.route('/web/operaciones/concentracionReport', auth="user")
    def download_document(self, filename=None, **kwargs):
        f = open('/home/odoo/.tmp/'+filename, 'rb')
        filecontent = f.read()
        if not filecontent:
            return request.not_found()
        else:
            if not filename:
                filename = filename + '.xls'
            os.remove('/home/odoo/.tmp/'+filename)
            return request.make_response(filecontent,
                                             [('Content-Type', 'application/octet-stream'),
                                              ('Content-Disposition', content_disposition(filename))])
```

**Comment by lmignon** [comment]
> I thought it was solved, but it was because I was not importing the controller that generates an Excel file with a report. It seems py3o is having a conflict with this controller:
> 
> Does any body has a clue what is the problem?
> 
> ```
> from odoo import http
> from odoo.http import request
> from addons.web.controllers.main import content_disposition
> import os
> 
> class urlConcentracionesReport(http.Controller):
> 
>     @http.route('/web/operaciones/concentracionReport', auth="user")
>     def download_document(self, filename=None, **kwargs):
>         f = open('/home/odoo/.tmp/'+filename, 'rb')
>         filecontent = f.read()
>         if not filecontent:
>             return request.not_found()
>         else:
>             if not filename:
>                 filename = filename + '.xls'
>             os.remove('/home/odoo/.tmp/'+filename)
>             return request.make_response(filecontent,
>                                              [('Content-Type', 'application/octet-stream'),
>                                               ('Content-Disposition', content_disposition(filename))])
> ```

@abrigard 
`download_documen`t is already a method provided by the base controller. Since you never call `super` and your addon is initialized/loaded after `base`, `py3o` ,  ... your method is at the top of the execution stack and breaks the inheritance....

**Comment by abrigard** [comment]
Thanks for your answer. I changed the name of the method to `d_file`, but is still there.

**Comment by lmignon** [comment]
@abaghirli I can't figure your problem.. As you noticed, it seems that there is a conflict somewhere between your addons and py3o. Maybe on the JS side or the controller side... You have to debug to understand the issue. That doesn't mean that the issue is not into py3o but I never encountered this problem in my projects were I use py3o.
