### ISSUE TITLE
[12.0] kpi_dashboard: Meter widget max value is 100 and does not take mix/max into account

### ISSUE THREAD

**Issue by llabusch93** [OCA/reporting-engine#428]
The meter widget does not take the "min" and "max" keys in the result dict into account, nor displays numbers for the "value" key, if they are bigger than 100 - then it just displays 100.

Example:

Having the following result dict:

`result = {"min": 0, "max": 600, "value": 250}`

will result in displaying just 100 in the meter widget.

This happens also in the demo data on runbot.

**Comment by etobella** [comment]
@llabusch93 Currently, the Meter is only available for percentages, but checking the documentation of GaugeMeter (https://github.com/Mictronics/GaugeMeter) it might be possible to set min and max value using min, total and used.

Would you like to try to make the PR?

**Comment by llabusch93** [comment]
@etobella 

yes I wanted to start to contribute to OCA anyway since ages, so being directly asked is a good motivation to finally do so I think ;). As I just returned from holidays and drowning in work, I will have time for this here in a few weeks, but there is no urgency, right?

I keep you posted in this thread once I started.
