### ISSUE TITLE
py3o How to show HTML Code in libreoffice with html_sanitize?

### ISSUE THREAD

**Issue by diezcode** [OCA/reporting-engine#434]
When I add a new py3o function to get the html code from a HTML field in Odoo, the libreoffice document is showing all the tags or the html_sanitize signs.
Is there any way to show HTML fields in the libreoffice document?

Is this a bug?

**Comment by cataclysmic** [comment]
I am having the same question. I want to export html field content using py3o but can't find a way to convert so that I get the same formatting in libreoffice.

**Comment by diezcode** [comment]
Hello @cataclysmic , We didn't find a solution so we moved to basic qweb reports for the future. There need to be changes in the py3o modules or core library to use odoo html fields in the libreoffice reports. If anyone has a solution I'm looking forward to it. 
Thanks.

**Comment by cataclysmic** [comment]
@diezcode Thank you for the feedback. I looked into wordinserter https://github.com/orf/wordinserter  but I don't tink it would work as a solution. An idea was to use html->docx using pandoc as a converter. I am looking for an export module that uses pandoc in the backend. Does anyone know an implementation?

**Comment by FSchiepers** [comment]
It is possible with https://github.com/OCA/server-tools/tree/15.0/html_text 
You create a calculated field with the code:

for record in self:
        record['x_CONVERTEDTEXT'] = self.env["ir.fields.converter"].text_from_html(self.HTMLTEXT)

and you put that field CONVERTEDTEXT it in the py3o report.

**Comment by TomaszKn** [comment]
> It is possible with https://github.com/OCA/server-tools/tree/15.0/html_text You create a calculated field with the code:
> 
> for record in self: record['x_CONVERTEDTEXT'] = self.env["ir.fields.converter"].text_from_html(self.HTMLTEXT)
> 
> and you put that field CONVERTEDTEXT it in the py3o report.

Hi
This is not correct for this question.
We lose html formatting.
