### ISSUE TITLE
13.0 report_xlsx multi-company bug

### ISSUE THREAD

**Issue by luc-demeyer** [OCA/reporting-engine#470]
Report_xlsx drops the 'allowed_company_ids' context field.
Instead of the allowed_company_ids of the session the default company_id of the user in present in the context.
The result is a record rule error messages when making a report when the selected company is different from the default company of the user.

This is caused by the following lines in the action_manager_report.js code:

                if (cloned_action.context.active_ids) {
                    new_url += "/" + cloned_action.context.active_ids.join(",");
                }
 In case of 'active_ids' the session context that is present in the 'cloned_action' is dropped.

**Comment by sbidoul** [comment]
@luc-demeyer this isssue is resolved, right ?

**Comment by luc-demeyer** [comment]
yes
