### ISSUE TITLE
xls engine

### ISSUE THREAD

**Issue by bealdav** [OCA/reporting-engine#49]
report_xls module use a lib, xlwt, which does not support recent format of Excel / LibreOffice

What the plan for next 3 years ?

Should we yet invest in xlwt ?

Here is new libraries http://www.python-excel.org/

IMHO, here is a good one https://xlsxwriter.readthedocs.org/

**Comment by sbidoul** [comment]
:+1: for xslxwriter

@bealdav have a look a #38 by @adrienpeiffer which provides a base module for xslx reports.
