### ISSUE TITLE
Precision regarding difference between KPI and KPI Dashboard

### ISSUE THREAD

**Issue by flotho** [OCA/reporting-engine#520]
Hi everyone,

sorry for this probably weird question.
I would like to know the difference between Kpi and Kpi dashboard.
I mean what are the recommandation and usages differences.
Both seems to be able to set up min and max value through code or config, both deal with periodical updates and store the values etc..
Any advice and clarifications would be appreciated.
Regards

**Comment by etobella** [comment]
Kpi is a system to store a single value and a comparison value. 

Kpi dashboard allows this and define other kind of indicators, like complex graphs. Also, you can see them together in a dashboard.

IMO Kpi is probably not needed anymore as functionality overlaps and dashboard includes some extra features

**Comment by flotho** [comment]
Hi @etobella 

Thanks for your feedback.
