### ISSUE TITLE
BI SQL Editor  - new SQL Views

### ISSUE THREAD

**Issue by b5baxter** [OCA/reporting-engine#521]
The first view I created with the BI SQL Editor took me through the steps to including SQL verification, view and model creation, etc.

However, when I go to create another new view,  it just opens a form.  I can edit some of the fields but there is no option to verify SQL or create the reports, models, cron jobs.

**Comment by legalsylvain** [comment]
Hi which version ? I don't understand exactly your problem. Could you provide screenshot / video ?
