### ISSUE TITLE
[12.0] report_label, resolution & label size

### ISSUE THREAD

**Issue by gregory-moka** [OCA/reporting-engine#535]
Hello @ivantodorovich,

I have some trouble with the addon we worked on, concerning the label template setting to get the good PDF rendering.
I set all the datas needed to generate the good label format, but, when I get the PDF document, the label are not exactly printed on the sticker.

**What I tried :** 

- to set the therical dimension written on the paperbox, once printed, the label are not as set in backend,
- to play with resolution (ppp) to see if it could fit, but, one time it's too large, one time it's too tiny..

**The label reder :** 
In light grey, the stickers area (where the label should be printed) and the label (which are defined with the black border)  
![Label](https://user-images.githubusercontent.com/45974412/133640252-c004b4d2-74a0-4988-99ed-fbb5351a1478.jpg)

Any ideas ?

**Comment by MalikaBelmokhtar** [comment]
Any feedback ?

**Comment by flotho** [comment]
di you tried to use parameter module and use disable-samrt shrinking : https://github.com/OCA/reporting-engine/tree/14.0/report_wkhtmltopdf_param#report-wkhtmltopdf-param

**Comment by flotho** [comment]
and BTW did you recreate a full QWEB tempate or use an existing one
