### ISSUE TITLE
ValueError: More than 4094 XFs (styles)

### ISSUE THREAD

**Issue by saltonmassally** [OCA/reporting-engine#55]
I am printing a QWEB report as XLS using the report_xls_template and it keeps giving me the error - ValueError: More than 4094 XFs (styles). 

Setting Workbook(style_compression=2) in the intiailization of Workbook() in report_sls_teplate line 272 solved the issue for m. see http://stackoverflow.com/questions/17130516/xlwt-set-style-making-error-more-than-4094-xfs-styles

**Comment by pedrobaeza** [comment]
Please propose a PR with your fix.

**Comment by pedrobaeza** [comment]
No answer, so I close
