### ISSUE TITLE
Not Working while printing report length from company

### ISSUE THREAD

**Issue by muhammadnaeem786** [OCA/reporting-engine#556]
It is not working properly i am unable to see its demo.

**Comment by pedrobaeza** [comment]
Which module? Which Odoo version? Detailed steps to reproduce the problem?

**Comment by etobella** [comment]
Also, did you test it locally or in runboat?

**Comment by muhammadnaeem786** [comment]
qweb_report_paremeter odoov13 yeah i have tested locally as well as on runboat.

**Comment by muhammadnaeem786** [comment]
![Screenshot from 2021-12-13 11-34-32](https://user-images.githubusercontent.com/84784929/145774788-73bc1aeb-1966-4956-8633-bfeebec8faca.png)

**Comment by pedrobaeza** [comment]
Detailed steps to reproduce the error?

**Comment by quyvsquy** [comment]
I have the same problem, I use odoo 15, while i install `report_xlsx` and print qweb report not working, after I uninstall `report_xlsx and qweb working normally.

**Comment by onurugur** [comment]
> I have the same problem, I use odoo 15, while i install `report_xlsx` and print qweb report not working, after I uninstall `report_xlsx and qweb working normally.

Hi, I am solving it  with changing the Promise.resolve(true) -- false

---
/report_xlsx/static/src/js/report/action_manager_report.esm.js
---

`            }
        }
        return Promise.resolve(false); # true --> false
    });` 
and its fixed

**Comment by stanleykao72** [comment]
> > I have the same problem, I use odoo 15, while i install `report_xlsx` and print qweb report not working, after I uninstall `report_xlsx and qweb working normally.
> 
> Hi, I am solving it with changing the Promise.resolve(true) -- false
> 
> ## /report_xlsx/static/src/js/report/action_manager_report.esm.js
> ` } } return Promise.resolve(false); # true --> false });` and its fixed

I have the same issue, when I change to "return Promise.resolve(false)" the qweb report face below log.

{"code": 200, "message": "Odoo Server Error", "data": {"name": "builtins.TypeError", "debug": "Traceback (most recent call last):\n File \"/home/odoo/src/odoo/addons/web/controllers/main.py\", line 2001, in report_download\n response = self.report_routes(reportname, docids=docids, converter=converter, context=context)\n File \"/home/odoo/src/odoo/odoo/http.py\", line 536, in response_wrap\n response = f(*args, **kw)\n File \"/home/odoo/src/user/report_xlsx/controllers/main.py\", line 49, in report_routes\n return super(ReportController, self).report_routes(\n File \"/home/odoo/src/odoo/odoo/http.py\", line 536, in response_wrap\n response = f(*args, **kw)\n File \"/home/odoo/src/odoo/addons/web/controllers/main.py\", line 1928, in report_routes\n data['context'] = json.loads(data['context'])\n File \"/usr/lib/python3.8/json/__init__.py\", line 341, in loads\n raise TypeError(f'the JSON object must be str, bytes or bytearray, '\nTypeError: the JSON object must be str, bytes or bytearray, not dict\n", "message": "the JSON object must be str, bytes or bytearray, not dict", "arguments": ["the JSON object must be str, bytes or bytearray, not dict"], "context": {}}}


I fixed it in main.py:

    @route()
    def report_routes(self, reportname, docids=None, converter=None, **data):
        report = request.env["ir.actions.report"]._get_report_from_name(reportname)
        context = dict(request.env.context)
        if converter == "xlsx":
            if docids:
                docids = [int(i) for i in docids.split(",")]
            if data.get("options"):
                data.update(json.loads(data.pop("options")))
            if data.get("context"):
                data["context"] = json.loads(data["context"])
                context.update(data["context"])

            xlsx = report.with_context(**context)._render_xlsx(docids, data=data)[0]
            xlsxhttpheaders = [
                (
                    "Content-Type",
                    "application/vnd.openxmlformats-"
                    "officedocument.spreadsheetml.sheet",
                ),
                ("Content-Length", len(xlsx)),
            ]
            return request.make_response(xlsx, headers=xlsxhttpheaders)
        return super(ReportController, self).report_routes(
            reportname, docids, converter, **data
        )
