### ISSUE TITLE
8.0 Crash in report_custom_filename

### ISSUE THREAD

**Issue by alexis-via** [OCA/reporting-engine#56]
Here is the scenario to reproduce the bug on an up-to-date Odoo v8 with up-to-date OCA/reporting-engine/8.0 branch:
1) Install the module report_custom_filename
2) Replace the native sale order report by an aeroo report (I guess the problem is the same with reporting engines other than Qweb)

To make it easier for you to reproduce the bug, I have prepared a small module "test_bug_reportfilename" that depend on report_aeroo and report_custom_filename and that replaces the native quotation report by a small aeroo report. Get it here:
http://people.via.ecp.fr/~alexis/test_bug_reportfilename.zip

3) In Settings > Technical > Actions > Report
Edit the report "Quotation / Order" and set the field "Download filename" to
Quote-currency-${o.currency_id.name}.pdf
This filename may be stupid, but it's easier to reproduce/understand the bug that way, with a field o.currency_id with is present on sale.order but not on res.partner.
4) Go to the Form view of the customer Agrolait, click on the "Sales" button, select the first quotation in the tree view and click on "Print": you get a crash:

```
Traceback (most recent call last):
  File "/home/alexis/new_boite/dev/odoo8/addons/web/controllers/main.py", line 70, in wrap
    return f(*args, **kwargs)
  File "/home/alexis/new_boite/dev/reporting-engines8/report_custom_filename/controllers/reports.py", line 49, in index
    'object': objects[0],
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python2.7/dist-packages/jinja2/sandbox.py", line 329, in getattr
    value = getattr(obj, attribute)
UndefinedError: 'openerp.api.res.partner object' has no attribute 'currency_id'
```

**Code analysis:**

Qweb reports use report_custom_filename/controllers/report_controller.py
Aeroo reports (and probably other report engines) use report_custom_filename/controllers/reports.py

In report_custom_filename/controllers/report_controller.py, the model that is used as a base for "o." is the model of the report. But, in report_custom_filename/controllers/reports.py, the model that is used as a base for "o." is context['active_model']. When you click on the "Sales" button in the form view of the partner, you arrive on the tree view of sale orders, but context['active_model'] is still "res.partner" (maybe a bug of the web client, I don't know...), which triggers the crash in report_custom_filename.

**Comment by alexis-via** [comment]
@hbrunn As you are the author of this great module, what do you think of this bug report and the fix I proposed.

**Comment by pedrobaeza** [comment]
@alexis-via, for other times, if you make a PR, I think it's better to directly report the issue in the same PR, instead of having 2 places for the discussion.

**Comment by alexis-via** [comment]
@pedrobaeza OK, next time I'll do only a PR, no bug report

**Comment by yvaucher** [comment]
#57 has been merged
