### ISSUE TITLE
Default PDF reports doesnt work after installing this module for Odoo 15

### ISSUE THREAD

**Issue by kbirkbr** [OCA/reporting-engine#580]
## Module
Base report xlsx (report_xlsx)

## Describe the bug
I installed this module in my odoo 15 database and created excel report. excel reports working fine. But after installing this module all PDF reports are not print. When click the print menu from print drop down nothing happening. no error on terminal and browser console.

## To Reproduce
**Affected versions**:Odoo 15 EE

1. install the report_xlsx module on odoo 15 EE database
2. open any sale order record 
3. try to print the opened sale order from print drop down menu.

**Expected behavior**
The PDF document should print/download

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by dcorio** [comment]
I can confirm this issue.
I'm pretty sure it was working on v15 on odoo.sh in December 2021, then something happend.

**Comment by dcorio** [comment]
Update: the problem was already fixed, I just needed to update the module. So this issue should be closed.
