### ISSUE TITLE
report_xlsx: report run in su mode

### ISSUE THREAD

**Issue by sbidoul** [OCA/reporting-engine#586]
## Module
report_xlsx

## Describe the bug
The method `generate_xlsx_report` ends being called with su=True. It should not as the reports ends up running without record rules.

This because it is invoked via `_render_xlsx` on the `ir.action.report` object, which itself comes from `_get_report_from_name` which looks up the action with sudo.

**Comment by pedrobaeza** [comment]
Patch merged, so closing.
