### ISSUE TITLE
14.0 failed to install requirements on latest pykcs11

### ISSUE THREAD

**Issue by flotho** [OCA/reporting-engine#592]
## Module

All the module are concerned by executing the command 

## Describe the bug

Trying to execute `pip install -r requirements.txt`

here is the result :
```
.../...
Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./pipenv/lib/python3.8/site-packages (from requests->endesive->-r /home/florent.thomas/DEV/_ProjetsOdoo/XXX/Libs/OCA-reporting-engine/requirements.txt (line 3)) (1.24.3)
Requirement already satisfied: idna<2.9,>=2.5 in ./pipenv/lib/python3.8/site-packages (from requests->endesive->-r /home/florent.thomas/DEV/_ProjetsOdoo/XXX/Libs/OCA-reporting-engine/requirements.txt (line 3)) (2.6)
Building wheels for collected packages: pykcs11
  Building wheel for pykcs11 (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'PyKCS11._LowLevel' extension
      swigging src/pykcs11.i to src/pykcs11_wrap.cpp
      swig -python -c++ -o src/pykcs11_wrap.cpp src/pykcs11.i
      unable to execute 'swig': No such file or directory
      error: command 'swig' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pykcs11
  Running setup.py clean for pykcs11
Failed to build pykcs11
Installing collected packages: pykcs11, asn1crypto, oscrypto, endesive
  Running setup.py install for pykcs11 ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pykcs11 did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running install
      running build
      running build_ext
      building 'PyKCS11._LowLevel' extension
      swigging src/pykcs11.i to src/pykcs11_wrap.cpp
      swig -python -c++ -o src/pykcs11_wrap.cpp src/pykcs11.i
      unable to execute 'swig': No such file or directory
      error: command 'swig' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pykcs11

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

## To Reproduce
**Affected versions**:

seems that the latest release of this dependency is causing troubles.
Tried to install the following releases : 

- PyKCS11-1.4.4 => success
- PyKCS11-1.5.0 and above => error 

seems we're not alone there : https://github.com/LudovicRousseau/PyKCS11/issues/62

shouldn't we precise that swig is necessary in a specific module as explained there : https://github.com/automl/auto-sklearn/issues/763#issuecomment-577180272

**Expected behavior**

installation succeed

**Additional context**

python 3.8 in pipenv

**Comment by MiquelRForgeFlow** [comment]
![Selection_236](https://user-images.githubusercontent.com/25005517/155526980-d47175e8-8f8b-406f-bbab-56da85bbc766.png)

**Comment by flotho** [comment]
Hi,
what could  be proper process to prevent this bad dependency?

**Comment by flotho** [comment]
installing swig by hand solved the issue.
how can we indicate this in any module ?

Regards

**Comment by francesco-ooops** [comment]
We have the same issue internally

**Comment by GSLabIt** [comment]
> installing swig by hand solved the issue.
> how can we indicate this in any module ?
> 
> Regards

What did u installed manually?

**Comment by francesco-ooops** [comment]
@OCA/reporting-engine-maintainers could you take a look at this?

thanks!

**Comment by flotho** [comment]
> > installing swig by hand solved the issue.
> > how can we indicate this in any module ?
> > Regards
> 
> What did u installed manually?

I installed `swig` http://www.swig.org/ available in my system repo.
and everything went fine afterwards

**Comment by GSLabIt** [comment]
> > > installing swig by hand solved the issue.
> > > how can we indicate this in any module ?
> > > Regards
> > 
> > What did u installed manually?
> 
> I installed `swig` http://www.swig.org/ available in my system repo.
> and everything went fine afterwards 

Yap, i figured it out. We missed g++  as well. Now it works fine, finally
