### ISSUE TITLE
Kpi Dashboard Altair Requirement Error

### ISSUE THREAD

**Issue by edoubleoo** [OCA/reporting-engine#598]
Hi all, 

I am trying to install Kpi Dashboard Altair on Odoo v12, the module requires Altair to be installed in to our available python library. I was able to install Altair using the 'pip3 install altair', but when I try to install the module within Odoo I get an invalid syntax response for the module requirement and terminate the module installation. 

Will this module only work with pip/2.7 request syntax?

Please advise

**Comment by etobella** [comment]
Odoo 12 must be executed with python3, so it has no sense to use pip, are you using the same python version from pip? how do you execute odoo? I mean, this error is usually because you installed altair on python3.7 and you are using python3.6 (or something like that)

**Comment by edoubleoo** [comment]
I used a 'pip3 install Altair' call, and the Altair-4.0.1 was installed.

Is this a pip 3.6 or 3.7 installation?

**Comment by etobella** [comment]
It depends on your configuration. I cannot say

**Comment by edoubleoo** [comment]
What I can say is I am using Odoo 12, Linux 4.4.180+ x86_64 (Docker), both Python 2.7 / 3.5.3 installed. 

I'm stuck woundering why Altair-4.0.1 is coming back as invalid syntax unless I need a specific version of Altair?

**Comment by etobella** [comment]
I cannot say. However, GH is working properly, so this is an issue with your installation. You should review which python is executing odoo

**Comment by edoubleoo** [comment]
At this point, I cannot define the issue, installed with both python 2.7 & python 3.5, had to use the pip3 request as pip has not been installed.

Both times completed "invalid syntax" is display when trying to install the module within Odoo.

# pip3 install altair
Collecting altair
  Using cached https://files.pythonhosted.org/packages/a8/07/d8acf03571db619ff117df5730dd5c0b1ad0822aa02ad1084d73e2659442/altair-4.0.1-py3-none-any.whl
Requirement already satisfied: jinja2 in /usr/lib/python3/dist-packages (from altair)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.5/dist-packages (from altair)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.5/dist-packages (from altair)
Requirement already satisfied: pandas in /usr/local/lib/python3.5/dist-packages (from altair)
Requirement already satisfied: toolz in /usr/local/lib/python3.5/dist-packages (from altair)
Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages (from altair)
Requirement already satisfied: MarkupSafe in /usr/lib/python3/dist-packages (from jinja2->altair)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.5/dist-packages (from jsonschema->altair)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python3.5/dist-packages (from jsonschema->altair)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.5/dist-packages (from jsonschema->altair)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.5/dist-packages (from pandas->altair)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.5/dist-packages (from pandas->altair)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.5/dist-packages (from importlib-metadata; python_version < "3.8"->jsonschema->altair)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.6.1->pandas->altair)
Installing collected packages: altair
Successfully installed altair-4.0.1
