### ISSUE TITLE
14.0 report_xlsx

### ISSUE THREAD

**Issue by lorenzoallegrucci** [OCA/reporting-engine#604]
## Module
report_xlsx

## Describe the bug
In case of thousands ids selected, this "new_url" would be huge:
https://github.com/OCA/reporting-engine/blob/14.0/report_xlsx/static/src/js/report/action_manager_report.js#L26
and would exceed to maximum url length in odoo.sh

## To Reproduce
**Affected versions**:

- [ ] 14.0

1. select thousands of ids from a tree
2. generate a report by report_xlsx
3. error "414 Request URI Too Large"

**Expected behavior**
a generated report of all ids without error

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by santcosta** [comment]
I think this happens in any other version... i have the same problem in odoo 11.
Did you find any solution ?

**Comment by etobella** [comment]
Did you tried to do the same with thousand of records for a pdf generation from a tree view?

**Comment by NothingCtrl** [comment]
This is really a problem when report data is big, because all is encoded to URI, I think we should switch to POST method.

**Comment by pedrobaeza** [comment]
PRs changing that are very welcome.
