### ISSUE TITLE
object has no attribute 'generate_report'

### ISSUE THREAD

**Issue by pythoniclad** [OCA/reporting-engine#622]
### Module
report_xml

### Issue:
object has no attribute 'generate_report
```
content, ttype = report_model.generate_report(
AttributeError: 'report.top_selling_product_report.top_selling_repo' object has no attribute 'generate_report'
```
### Expected behavior
XML report containing all top selling products from sale order downloaded

**Comment by pedrobaeza** [comment]
Please check examples like https://github.com/OCA/l10n-spain/tree/14.0/l10n_es_facturae, but the module works. Closing as no issue with the module itself, but custom development.

**Comment by pythoniclad** [comment]
> Please check examples like https://github.com/OCA/l10n-spain/tree/14.0/l10n_es_facturae, but the module works. Closing as no issue with the module itself, but custom development.

Thanks for help, how do I ask question related to custom development ? and do you have example of any other custom module dependent upon **report_xml** because use of **generate_report** function still not comprehensible for me.

**Comment by pedrobaeza** [comment]
Ask on the forums or mailing list.
