### ISSUE TITLE
report_csv print lines without headers

### ISSUE THREAD

**Issue by mostafaala2** [OCA/reporting-engine#632]
in module Base report csv
i need to print data in two lines like 
x,y
A,B,C,d
module forces me to put headers 
    res['fieldnames'].append('A')
      res['fieldnames'].append('B')
      res['fieldnames'].append('C')
      res['fieldnames'].append('D')
      res['fieldnames'].append('E')

and the results are:
x,y, ,  two additional commas added 
A,B,C,d,e
what is the solution to this problem

**Comment by opheli2003** [comment]
Did you find a solution ?
