### ISSUE TITLE
About bi_sql_editor Decimal Accuracy 

### ISSUE THREAD

**Issue by szegc** [OCA/reporting-engine#643]
Dear suport,
       Thank you for provide this module(v13),when i test to use it,i found when a float like 0.378（decimal places more than 2）,it's only display as 0.38,i didn't found where i can set or change it,could you help to solve it?

Best regards.
Michael

**Comment by thomaspaulb** [comment]
You can only set it globally in Odoo, in Technical Settings -> Database Structure -> Decimal Accuracy.

**Comment by szegc** [comment]
Hi Tom,
      Yet we already set Product Price as 3 in Decimal Accuracy.



Best Regards.
Michael Wu
 
From: Tom
Date: 2022-08-30 12:00
To: OCA/reporting-engine
CC: szegc; Author
Subject: Re: [OCA/reporting-engine] About bi_sql_editor Decimal Accuracy (Issue #643)
You can only set it globally in Odoo, in Technical Settings -> Database Structure -> Decimal Accuracy.

**Comment by thomaspaulb** [comment]
You can try changing the other ones that are there.

Otherwise a change to the module is required, maybe a "precision" variable should be added here: 

https://github.com/OCA/reporting-engine/blob/6fb7869dc509d735be3cd3cacf227b71f4f9d898/bi_sql_editor/models/bi_sql_view_field.py#L209
