### ISSUE TITLE
bi_sql_editor conflict with Odoo studio

### ISSUE THREAD

**Issue by randyraharjo93** [OCA/reporting-engine#648]
## Module
bi_sql_editor

## Describe the bug
Error on Studio, saying KeyError: base.automation.model_name [https://postimg.cc/hQPBJshN](url)

## To Reproduce
**Affected versions**: 14,15

1. Have bi_sql_editor installed
2. Make sure you have at least 1 sql is running (ie: already generate the menu, ui, etc)
3. Try to edit some form view in studio, try to modify (add field, edit field name) for 10-20 times consecutively in a single studio session
4. Error message should pop up

**Expected behavior**
No error happens

**Additional context**
Happens on Odoo.sh, on premise, etc.

**Comment by randyraharjo93** [comment]
@legalsylvain Sorry I mentioned, but it seems you are the current maintainer.

**Comment by legalsylvain** [comment]
Hi @randyraharjo93. Thanks for reporting. I don't have access to odoo studio as it is private. I'll so can not investigate about your bug.

Good luck, and don't hesitate to ping me if you do a PR.
