### ISSUE TITLE
[13.0] [bi_view_editor] Backport bi_view_editor for Odoo 13

### ISSUE THREAD

**Issue by wekeesler** [OCA/reporting-engine#665]
My organization is interested in using the bi_view_editor module in our Odoo 13 instance. I see that the module was migrated and merged into the 14.0 branch, but the 13.0 branch was skipped. I have tested the 14.0 version of the module in Odoo 13 and verified it works with minor changes:

* Setting the module version back to 13.0.
* Replacing `self.env["res.lang"]._activate_lang("it_IT")` with `self.env["res.lang"].load_lang('it_IT')` in the `test_18_action_translations` test.

I am wondering if it possible to backport/migrate the module to 13.0. I am willing to help by creating a pull request if that is preferable.

**Comment by legalsylvain** [comment]
Hi. @wekeesler Thanks for your proposal.

You can follow the OCA guidelines written here https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#how-to
but replacing 12.0 by 14.0
Then commit your changes and propose a PR.

Kind regards.
