### ISSUE TITLE
[14.0]Report Label produce empty PDF with default label format agipa

### ISSUE THREAD

**Issue by flotho** [OCA/reporting-engine#705]
Hi,

I'm trying to use the report label module.
Here is the default setup I used.

![image](https://user-images.githubusercontent.com/1043935/209961191-708171cd-4781-4ce4-b4e0-0b74c6992d6c.png)

Sadly, this configuration produce an empty PDF, is there any restriction regarding python module version or wkhtml ?

**Comment by flotho** [comment]
Here is the version of wkhtml : 
![image](https://user-images.githubusercontent.com/1043935/209964462-c093f202-c50d-467c-830e-a3e02ebc81f4.png)

**Comment by flotho** [comment]
looks like it produce something but still empty :+1: 
![image](https://user-images.githubusercontent.com/1043935/209969913-797337d4-8b3a-42c3-aa3a-2bd9b7ac0437.png)

[Label Report.pdf](https://github.com/OCA/reporting-engine/files/10320048/Label.Report.pdf)

**Comment by legalsylvain** [comment]
Did you created / reused the qweb report ?

See : https://github.com/OCA/reporting-engine/tree/14.0/report_label#id1

**Comment by flotho** [comment]
I reused the original one in v14 
![image](https://user-images.githubusercontent.com/1043935/209978305-97bf6d2d-f1a6-4e26-b2ef-2093e33eb4d5.png)

this report is looping :
![image](https://user-images.githubusercontent.com/1043935/209978389-9e4eee29-d72b-4e76-a501-466c3a5aef2d.png)

maybe I need to create a new one ?

Your advice is welcome

**Comment by legalsylvain** [comment]
> maybe I need to create a new one ?

I dont think, if it doesnt work with the default one. 

Did you tried on runboat ?

**Comment by flotho** [comment]
hum... the demo template helps a lot for the analysis, the template must use the record variable and the original one are not using this variable nam, I'll check

**Comment by flotho** [comment]
tadaaamm!!!
That's it.
