### ISSUE TITLE
[16.0]BI SQL EDITOR dependency

### ISSUE THREAD

**Issue by flotho** [OCA/reporting-engine#768]
Hi,

As there is now an OCA spreadsheet repo, I'm wondering if letting the BI SQL EDITO inherit from Odoo core one is a good solution?
Any feedback?

**Comment by legalsylvain** [comment]
Hi @flotho. 
The objective of bi_sql_editor module for the time being, is to create new model, on a new postgresql view (materialized or not) named ``x_bi_sql_view_xxx``, based on a simple or complex SQL request.
Then the model is accessible in readonly by tree, form, pivot views.
At this step, the pivot view can be "consumed" by the spreadsheet module.

I don't understand what you imagine, but I don't know very well the new spreadsheet modules, and I don't know the roadmap of this project.

Could you elaborate your question ? describing features, possibilities, etc...

Thanks ! 

CC : FYI @etobella.

**Comment by flotho** [comment]
Hi @legalsylvain 
thanks for your answer. I should have badly wrote my thoughts.
As you can see here https://github.com/OCA/reporting-engine/blob/16.0/bi_sql_editor/__manifest__.py#L14 this module inherits from spreadsheet_dashboard, the odoo one.
I'm wondering if it wouldn't be better to inherits from OCA one or to add a glue module that could use either OCA ones or Odoo one.

**Comment by flotho** [comment]
my bad (facepalm)
the OCA one already depends on the Odoo one : https://github.com/OCA/spreadsheet/blob/16.0/spreadsheet_dashboard_oca/__manifest__.py#L13
totally useless issue from me, sorry for the noise

**Comment by legalsylvain** [comment]
;-)
I didn't know that module, so thanks for the information !
