### ISSUE TITLE
View Joining to "_unknown" Relation Error

### ISSUE THREAD

**Issue by jtempletmg** [OCA/reporting-engine#806]
## Module
bi_sql_editor

## Describe the bug
I can successfully create a View using the BI SQL Editor module but when trying to view the data drilling down on product or team causes an error.  The SQL Fields tab lists those fields as a many2one but there is no related model.

## To Reproduce
**Affected versions**: 14.0

1.  Create the following view/create ui/open view:
select 
	categ_id as x_categ_id
	, commercial_partner_id as x_commercial_partner_id
	, company_id as x_company_id
	, key_team_id as x_key_team_id
	, key_team_leader_id as x_key_team_leader_id
	, partner_id as x_partner_id
	, product_brand as x_product_brand
	, product_id as x_product_id
	, product_tmpl_id as x_product_tmpl_id
	, product_uom as x_product_uom
	, product_uom_qty as x_product_uom_qty
	, team_id as x_team_id
	, sum(OrderTotal) as x_order_total
	, sum(InvoiceTotal) as x_invoice_total
from
	(
		select
			categ_id
		    , commercial_partner_id
		    , company_id
		    , key_team_id
		    , key_team_leader_id
		    , partner_id
		    , sum(remaining_amount) as OrderTotal
		    , 0 as InvoiceTotal
		    , product_brand
		    , product_id
		    , product_tmpl_id
		    , product_uom
		    , product_uom_qty
		    , team_id
		from 
			sale_report
		where
			state = 'sale'
			and invoice_status = 'no'
		group by 
			categ_id
		    , commercial_partner_id
		    , company_id
		    , key_team_id
		    , key_team_leader_id
		    , partner_id
		    , product_brand
		    , product_id
		    , product_tmpl_id
		    , product_uom
		    , product_uom_qty
		    , team_id
		union
		select
			pt.categ_id
		    , commercial_partner_id
		    , am.company_id
		    , key_team_id
		    , kct.user_id as key_team_leader_id
		    , am.partner_id
			, 0 as OrderTotal
			, sum(aml.price_subtotal) as InvoiceTotal		
		    , product_brand
		    , aml.product_id as product_id
		    , pp.product_tmpl_id as product_tmpl_id
		    , product_uom_id as product_uom
		    , quantity as product_uom_qty
		    , ct.id as team_id
		from
			account_move am
			join account_move_line aml on am.id = aml.move_id
			left outer join product_product pp on aml.product_id = pp.id
			left outer join product_template pt on pp.product_tmpl_id = pt.id
			left outer join crm_team kct on am.key_team_id = kct.id
                        left outer join crm_team ct on am.team_id = ct.id
		where
			move_type in ('out_invoice', 'out_refund')
			and am.state = 'posted'
			and aml.exclude_from_invoice_tab = False
		group by
			pt.categ_id
		    , am.commercial_partner_id
		    , am.company_id
		    , key_team_id
		    , kct.user_id
		    , am.partner_id
		    , product_brand
		    , aml.product_id
		    , pp.product_tmpl_id
		    , product_uom_id 
		    , quantity
		    , ct.id
	) as ForecastInfo
group by
	categ_id
	, commercial_partner_id
	, company_id
	, key_team_id
	, key_team_leader_id
	, partner_id
	, product_brand
	, product_id 
	, product_tmpl_id
	, product_uom
	, product_uom_qty
	, team_id

2. Drill down on "product_id" or "team_id"
3. An error is displayed in the log:
2023-11-06 19:46:09,350 4 ERROR themagnetgroup-odoo-sandbox-10276568 odoo.sql_db: bad query: 
            SELECT min("x_bi_sql_view_tmgforecast".id) AS id, count("x_bi_sql_view_tmgforecast".id) AS "__count" , sum("x_bi_sql_view_tmgforecast"."x_invoice_total") AS "x_invoice_total",sum("x_bi_sql_view_tmgforecast"."x_order_total") AS "x_order_total","x_bi_sql_view_tmgforecast"."x_product_id" as "x_product_id" 
            FROM "x_bi_sql_view_tmgforecast" LEFT JOIN "_unknown" AS "x_bi_sql_view_tmgforecast__x_product_id" ON ("x_bi_sql_view_tmgforecast"."x_product_id" = "x_bi_sql_view_tmgforecast__x_product_id"."id")
            WHERE TRUE
            GROUP BY "x_bi_sql_view_tmgforecast"."x_product_id","x_bi_sql_view_tmgforecast__x_product_id"."id"
            ORDER BY  "x_bi_sql_view_tmgforecast__x_product_id"."id"  
            
            
        
ERROR: relation "_unknown" does not exist
LINE 3: ...       FROM "x_bi_sql_view_tmgforecast" LEFT JOIN "_unknown"...
                                                             ^
2023-11-06 19:46:09,351 4 ERROR themagnetgroup-odoo-sandbox-10276568 odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 370, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 358, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 544, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1370, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1362, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 400, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 373, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/models.py", line 2258, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/home/odoo/src/odoo/odoo/models.py", line 2385, in _read_group_raw
    self._cr.execute(query, where_clause_params)
  File "<decorator-gen-5>", line 2, in execute
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 301, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.UndefinedTable: relation "_unknown" does not exist
LINE 3: ...       FROM "x_bi_sql_view_tmgforecast" LEFT JOIN "_unknown"...
                                                             ^
**Expected behavior**
product_id and team_id should be related to the correct module (unless I'm doing something wrong, which is highly likely)

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by legalsylvain** [comment]
what is the setting of the "fields" tab ?

**Comment by jtempletmg** [comment]
![image](https://github.com/OCA/reporting-engine/assets/30485733/2c51f1bc-2f64-43c9-b47a-f9d4b76b48d6)

**Comment by legalsylvain** [comment]
You should set model for each many2one fields. This should fix your issue.

Regards.

**Comment by jtempletmg** [comment]
Unfortunately you can't edit the data in SQL Fields once the view is validated.

**Comment by legalsylvain** [comment]
Yes you have to set your request in draft state again.

**Comment by jtempletmg** [comment]
Tried that.  When you set it back to Draft the SQL Fields tab is hidden:

![image](https://github.com/OCA/reporting-engine/assets/30485733/7bb6b5fd-d429-4cf7-b949-88ad777168a6)

**Comment by jtempletmg** [comment]
Now I get what you were trying to tell me!  You have to click "Validate SQL Expression" THEN you can edit the SQL Fields and set the related model! Thanks a bunch!
