### ISSUE TITLE
Not able to use report_xlsx version 17.0

### ISSUE THREAD

**Issue by purevmaa-coremind** [OCA/reporting-engine#834]
module: report_xlsx
version: 17.0

**Steps to reproduce**
- cloned reporting-engine and added report_xlsx into our custom-addons directory. Then, tried to install/upgrade from Apps menu on odoo, but receives SQL 1023

**Current behavior** 
- The company I work uses Odoo and we have started migrating our server from Odoo13 to Odoo17 as it is being demanded by Odoo. The most of our custom modules use report_xlsx. Unfortunately, we are facing the issue with the report_xlsx as it keep giving us the error of 'SQL 1023' when trying to see Module Info as well as our custom module which inherits from report_xlsx is not getting registered on database.

**Expected behavior**

**Comment by legalsylvain** [comment]
what is SQL 1023 ? could you copy paste the log ? Thanks !

**Comment by purevmaa-coremind** [comment]
Error Message Shown on Screen: "Can't fetch record(s) 1023. They might have been deleted." and there is no log on terminal.
![screenshot](https://github.com/OCA/reporting-engine/assets/152130464/109180b9-1fdf-42fe-854f-eb0f36e61003)

**Comment by purevmaa-coremind** [comment]
**Oh here is the log:**
2023-12-27 07:27:54,473 6582 WARNING mydb odoo.tools.cache: cache lookup error on ('ir.module.module', <function IrModule._get_modules_from_apps at 0x7faa2e201120>, ['icon_image', 'write_date', 'shortdesc', 'summary', 'author', 'website', 'state', 'to_buy', 'has_iap', 'module_type', 'description_html', 'display_name'], False, 'report_xlsx', None, None, None) 
Traceback (most recent call last):
  File "/home/user/Documents/odoo_v17/odoo/odoo/tools/cache.py", line 99, in lookup
    r = d[key]
  File "<decorator-gen-5>", line 2, in __getitem__
  File "/home/user/Documents/odoo_v17/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/user/Documents/odoo_v17/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
TypeError: unhashable type: 'list'
**Note:** I have done nothing but copy and paste the report_xlsx and run the odoo17 server to install the Base report application

**Comment by Mantux11** [comment]
@purevmaa-coremind  Hey. I used this module in our one of many reports that depends from this. It works like it should. Seeing a picture that you posted above, I have a workaround to install it. Just find this module in list view, delete it, Update App List using Odoo Debug and try to install. It should work. This bug I think is from Odoo core, not OCA, because I had received this error with different modules that ar not from OCA but after finding workaround, just don't kept that in mind.

**Comment by purevmaa-coremind** [comment]
@Mantux11 Thank you for your response. Yes, I have figured it is from Odoo and I have been updating/installing from list view it worked. Even if I do it from terminal, it works fine and my reports are working fine as expected.
