### ISSUE TITLE
Package odoo15-addon-report-xlsx not on Pipy

### ISSUE THREAD

**Issue by OpenCode** [OCA/reporting-engine#838]
The version **15.0** of the module **report_xlsx** is not on Pypi https://pypi.org/project/odoo15-addon-report-xlsx/ but the module is in the branch https://github.com/OCA/reporting-engine/tree/15.0/report_xlsx

The same thing happens for version **16.0**: https://pypi.org/project/odoo16-addon-report-xlsx/ and https://github.com/OCA/reporting-engine/tree/16.0/report_xlsx

**17.0** is OK: https://pypi.org/project/odoo-addon-report-xlsx/

Is there a particular reason? Or was it simply some error in one of the CI pipes?

## Module
report_xlsx

**Comment by OpenCode** [comment]
@sbidoul Maybe you might have an answer

**Comment by sbidoul** [comment]
Since 15 we don't have the Odoo series in the distribution name anymore, because the pip resolver is now smart enough to select the correct version based on the installed Odoo version.

So odoo-addon-report-xlsx has versions for 15 and 16 too: https://pypi.org/project/odoo-addon-report-xlsx/#history

**Comment by OpenCode** [comment]
> Since 15 we don't have the Odoo series in the distribution name anymore, because the pip resolver is now smart enough to select the correct version based on the installed Odoo version.
> 
> So odoo-addon-report-xlsx has versions for 15 and 16 too: https://pypi.org/project/odoo-addon-report-xlsx/#history

Thank you very much for the explanation. You have been comprehensive as always :)
