### ISSUE TITLE
[14.0] BI_SQL - Error in Pivot View

### ISSUE THREAD

**Issue by rodmad85** [OCA/reporting-engine#875]
When creating a query in bi_sql, the last line of the query is not shown and the values are positioned in the previous line. Example: 05/01/2024 has the values of 06/01/2024 in the Pivot view. However, the direct test in the query shows the values correctly.

Query:

WITH hr_summary AS (
    SELECT 
        DATE_TRUNC('month', check_in) AS x_data_check_in,
        SUM(CASE WHEN retrabalho THEN normal_total ELSE 0 END) AS x_total_retrabalho,
        SUM(extra_total) AS x_total_extra,
        SUM(normal_total) AS x_total_normal,
        SUM(valor_total) AS x_valor_total
    FROM 
        hr_attendance
    GROUP BY 
        DATE_TRUNC('month', check_in)
),
sale_summary AS (
    SELECT 
        DATE_TRUNC('month', date_order) AS x_month_date_order,
        SUM(horas_mo) AS x_total_mo_horas,
        SUM(valor_horas) AS x_valor_mo_horas
    FROM 
        sale_order
    WHERE 
        state = 'sale'
    GROUP BY 
        DATE_TRUNC('month', date_order)
)
SELECT 
    hr_summary.x_data_check_in,
    hr_summary.x_total_retrabalho,
    hr_summary.x_total_extra,
    hr_summary.x_total_normal,
    hr_summary.x_valor_total,
    sale_summary.x_total_mo_horas,
    sale_summary.x_valor_mo_horas
FROM 
    hr_summary
LEFT JOIN sale_summary ON hr_summary.x_data_check_in = sale_summary.x_month_date_order

![Captura de tela de 2024-05-02 10-27-38](https://github.com/OCA/reporting-engine/assets/74546/a5f8649f-f7f0-4f90-b927-3f96185f5bfa)

**Comment by legalsylvain** [comment]
Hi @rodmad85. 

At the first sight, you are talking about a datetime field. If you visualize with "direct test", you'll see the database value in UTC. If you visualize in odoo, you'll see in your timezone. That is a native odoo feature.


That being said, it's hard to identify a bug without possibility to reproduce. 
could you try to create an SQL request that are failing in a demo instance. (that can fail on OCA runbaot for instance ?) Closing in the meantime. Feel free to reopen, if you find a way to provide a demo request that is failing.
Thanks !

**Comment by rodmad85** [comment]
I tested by changing the user timezone to UTC and now the data is shown correctly. Can you tell me where I can put this change in SQL?

**Comment by rodmad85** [comment]
A friend from OCA from Brazil suggested the following correction suggestion:
[https://github.com/OCA/reporting-engine/pull/596/files](url)

**Comment by rvalyi** [comment]
@legalsylvain while talking with @rodmad85 and @marcelsavegnago on a Brazilian Telegram localization channel, it seems related to the PR attempt here:
https://github.com/OCA/reporting-engine/pull/596

BTW we think the conversion should use the user timezone rather than a global timezone as in the mentioned PR.

**Comment by rvalyi** [comment]
also possibly related to this Forgeflow PR that got merged in v10:
https://github.com/OCA/reporting-engine/pull/298

**Comment by legalsylvain** [comment]
hi.
- #298 is effective in v14. (https://github.com/OCA/reporting-engine/blob/14.0/bi_sql_editor/models/bi_sql_view_field.py#L48)
 - #596 indeed should be ported in recent version. But it is unrelated with the current problem of @rodmad85. It is about the display of the name of the action.

> BTW we think the conversion should use the user timezone rather than a global timezone as in the mentioned PR.

I fear that is tecnically impossible.
