### ISSUE TITLE
Does not work on Odoo 14

### ISSUE THREAD

**Issue by zhumxcq** [OCA/reporting-engine#877]
On odoo14, report_xlsx cannot be installed.

report_xlsx/controllers/main.py line 19
from odoo.addons.web.controllers.report import ReportController

but report.py does not exist in web controllers, it needs to be changed to
from odoo.addons.web.controllers.main import ReportController

**Comment by legalsylvain** [comment]
Hi. @zhumxcq. 
- How do you explain CI is green on V14 branch?
- could you make a PR ?

**Comment by zhumxcq** [comment]
Hi @legalsylvain 

Its not really for me to explain why CI is green on V14 branch. Its very clear to see that it won't install on Odoo14:
https://github.com/odoo/odoo/tree/14.0/addons/web/controllers
there is no report.py in that folder, but only main.py in that folder

I'm traveling and don't always have the best internet connection. The repo is too big for me to clone to do a pull request, but its a simple 1 line change to fix the issue.

**Comment by legalsylvain** [comment]
Hi. Thanks for your answer. 

> Its very clear to see that it won't install on Odoo14

Well for me it's not very clear ! Step to reproduce : 
 -go to oca runboat
http://oca-reporting-engine-14-0-ff04450ae28d.runboat.odoo-community.org/web/login
- log as admin/admin
- you'll see that the module is well installed.

Closing. Feel free to reopen if you can provide a bug.
Regards.

**Comment by pedrobaeza** [comment]
You don't have the proper latest code for for report_xlsx. On the latest one, the import is totally correct: 

https://github.com/OCA/reporting-engine/blob/ff04450ae28d9e6e8f6f85fbaca8197f39e89329/report_xlsx/controllers/main.py#L10
