### ISSUE TITLE
BI_VIEW_EDITOR for multi-company

### ISSUE THREAD

**Issue by micihn** [OCA/reporting-engine#879]
So, if there is a multi-company, the report will show from all companies. I don't know any way to filter this except to manage the filters from developer mode.

I think it's good to have a multi-companies security from the module, so the user can't delete the filter and see all records from all companies.

**Comment by victor-champonnois** [comment]
I agree this would be nice to have. The alternative so far is to use bi_sql_editor, that has multicompany support

**Comment by legalsylvain** [comment]
Hi @micihn you can create a dedicated ir.rule. this should do the job.
