### ISSUE TITLE
9.0 report_custom_filename incorrect migration

### ISSUE THREAD

**Issue by pedrocs-exo** [OCA/reporting-engine#91]
Hi,

I'm having a crash on the combination of report_custom_filename + report_xml on v9. I've identified the cause and decided to report. On method 'index' of class 'Reports' we have the following code:
v8
        _report_xml = http.request.session.model('ir.actions.report.xml')
        report_ids = report_xml.search(
            [('report_name', '=', action['report_name'])],
            0, False, False, context)
        for report in report_xml.browse(report_ids):
            if not report.download_filename:
                continue_
v9
        _report_xml = http.request.session.model('ir.actions.report.xml')
        reports = report_xml.search(
            [('report_name', '=', action['report_name'])],
            0, False, False, context)
        for report in reports:
            **if not report.download_filename:**
                continue_
the crash trace shows that on the line before the last one 'report' is an int so it couldn't possibly have a download_filename method. I think the developer applied a standard v8 to v9 API migration that doesn't apply to http requests. Keeping the v8 version solves the issue.

**Comment by pedrobaeza** [comment]
Can you please make a PR with the solution, as it's not very clear from the issue? You can do it directly from GitHub editing the affected file.

**Comment by pedrobaeza** [comment]
As now answer, I close.
