### ISSUE TITLE
How to implement an if-condition

### ISSUE THREAD

**Issue by ClaudiusMBio** [OCA/reporting-engine#97]
Hi ,

I'm using report_custom_filename in odoo8. Is it possible to add an if in the field? I tried 

`%if object.state in ('open','paid'): Invoice ${object.number} ${datetime.datetime.today()}.pdf`

I wonder why if-condition not ends after ":" Any ideas whats going wrong?

Greetings, Claudius

**Comment by pedrobaeza** [comment]
This is not an issue, but a question, but here it's the answer anyway: use the ternary operator x if y else z: http://stackoverflow.com/a/394814
